#!/usr/bin/env python3
"""
learn.py — Manual Learning Ingestion CLI
=========================================
Feeds framework knowledge from your own observations — rules, pitfalls,
patterns — into the AI pipeline's knowledge files.

Usage
-----
  python learn.py "your observation"          # inline arg
  python learn.py                             # interactive prompt
  python learn.py --dry-run "observation"     # print analysis only, no writes
  python learn.py --file notes.txt            # ingest multiple lines from a file
  python learn.py --type RULE "..."           # force type (RULE | PATTERN | PITFALL)

What happens
------------
1. The LLM reads your observation.
2. It searches existing framework_rules.md and framework_knowledge.md for
   semantically similar content.
3. Verdict: NEW | CORRECTION | DUPLICATE
4. Actions:
   - NEW RULE      → append to config/framework_rules.md
   - NEW PATTERN   → append to config/framework_knowledge.md
   - CORRECTION    → locate and replace the outdated paragraph in the right file
   - PITFALL       → also add to .github/copilot-instructions.md Common Pitfalls
   - DUPLICATE     → print message and skip
5. Persist to logs/learnings.jsonl with dedup.
6. Print a diff-style summary.
"""

import argparse
import json
import re
import sys
import threading
from datetime import datetime
from pathlib import Path

# ── Bootstrap path so config/* imports work when run from workspace root ──
_HERE = Path(__file__).resolve().parent
if str(_HERE) not in sys.path:
    sys.path.insert(0, str(_HERE))

from langchain_core.messages import HumanMessage, SystemMessage

from agents.llm_factory import get_llm
from config.project_config import BASE_DIR, LEARNINGS_LOG_PATH, OLLAMA_MODEL, OLLAMA_BASE_URL


def _make_llm(provider: str | None = None, temperature: float = 0.1):
    """Build an LLM instance.  If `provider` is given it overrides .env config."""
    if provider is None:
        return get_llm(temperature)
    p = provider.lower()
    if p == "ollama":
        from langchain_ollama import ChatOllama
        print(f"[LLM] Using Ollama → {OLLAMA_MODEL}")
        return ChatOllama(model=OLLAMA_MODEL, base_url=OLLAMA_BASE_URL, temperature=temperature)
    if p == "openai":
        from langchain_openai import ChatOpenAI
        from config.project_config import OPENAI_MODEL, OPENAI_API_KEY
        print(f"[LLM] Using OpenAI → {OPENAI_MODEL}")
        return ChatOpenAI(model=OPENAI_MODEL, api_key=OPENAI_API_KEY, temperature=temperature)
    # default / openrouter
    return get_llm(temperature)

# ── File paths ─────────────────────────────────────────────────────────────
_BASE             = Path(BASE_DIR)
_RULES_FILE       = _BASE / "config" / "framework_rules.md"
_KNOWLEDGE_FILE   = _BASE / "config" / "framework_knowledge.md"
_COPILOT_FILE     = _BASE / ".github" / "copilot-instructions.md"
_LEARNINGS_LOG    = Path(LEARNINGS_LOG_PATH)

_LEARNED_RULES_HEADER    = "\n\n---\n\n## LEARNED RULES (auto-generated by LearningAgent)\n"
_LEARNED_PATTERNS_HEADER = "\n\n---\n\n## LEARNED PATTERNS (auto-generated by LearningAgent)\n"

_file_lock = threading.Lock()

# ── ANSI colours ───────────────────────────────────────────────────────────
_GREEN  = "\033[32m"
_YELLOW = "\033[33m"
_RED    = "\033[31m"
_CYAN   = "\033[36m"
_BOLD   = "\033[1m"
_RESET  = "\033[0m"

def _ok(msg: str)   -> str: return f"{_GREEN}✅ {msg}{_RESET}"
def _warn(msg: str) -> str: return f"{_YELLOW}⚠️  {msg}{_RESET}"
def _err(msg: str)  -> str: return f"{_RED}❌  {msg}{_RESET}"
def _info(msg: str) -> str: return f"{_CYAN}ℹ  {msg}{_RESET}"
def _h(msg: str)    -> str: return f"{_BOLD}{msg}{_RESET}"


# ── Helpers ────────────────────────────────────────────────────────────────

def _read_file(path: Path) -> str:
    return path.read_text(encoding="utf-8") if path.exists() else ""


def _extract_headings(path: Path) -> str:
    """Extract all ## and ### headings from a markdown file as a compact index."""
    if not path.exists():
        return ""
    return "\n".join(
        line.strip()
        for line in path.read_text(encoding="utf-8").splitlines()
        if line.startswith("##") or line.startswith("###")
    )


def _extract_section(path: Path, heading: str) -> str:
    """Extract the full text block under the given heading."""
    text = _read_file(path)
    heading_clean = heading.lstrip("# ").strip()
    pattern = re.compile(
        r"(###[^\n]*" + re.escape(heading_clean) + r"[^\n]*\n)"
        r"(.*?)"
        r"(?=\n###|\n##|\Z)",
        re.DOTALL | re.IGNORECASE,
    )
    m = pattern.search(text)
    return (m.group(0) if m else "")[:800]


def _build_analysis_prompt(observation: str, rules_index: str, knowledge_index: str,
                            forced_type: str | None) -> str:
    type_hint = (f"\nIMPORTANT: The user has forced learning_type = {forced_type}. Honour it.\n"
                 if forced_type else "")
    return f"""You are an expert code-quality analyst for a Selenium / Java QA automation framework.

A developer typed an observation. Your tasks:

1. Classify as RULE (do/don't coding pattern) or PATTERN (working recipe to reuse)
   or PITFALL (critical gotcha — goes into both knowledge file AND copilot pitfalls list).
2. Judge EFFECTIVENESS: is this actionable? Mark ineffective=true if it is vague or trivial.
3. Check HEADINGS INDEX below for semantically similar topics:
   - DUPLICATE   → a matching topic already exists
   - CORRECTION  → a topic exists but the observation corrects or extends it
   - NEW         → genuinely not covered
{type_hint}
HEADINGS in framework_rules.md:
<rules_index>
{rules_index}
</rules_index>

HEADINGS in framework_knowledge.md:
<knowledge_index>
{knowledge_index}
</knowledge_index>

DEVELOPER OBSERVATION:
"{observation}"

Return a single JSON object with EXACTLY these keys (no extra text, no markdown):
{{
  "verdict":                     "NEW" | "CORRECTION" | "DUPLICATE",
  "ineffective":                 true | false,
  "ineffective_reason":          "short string or null",
  "learning_type":               "RULE" | "PATTERN" | "PITFALL",
  "title":                       "Short title (5-10 words)",
  "section":                     "SECTION N — relevant section name",
  "rule_type":                   "DO" | "DON'T" | null,
  "body":                        "2-4 sentence explanation (generic, not entity-specific)",
  "bad_example":                 "Java snippet or null",
  "good_example":                "Java snippet or null",
  "existing_heading_to_replace": "Exact ### heading text to replace for CORRECTION, or null",
  "replacement_body":            "Full replacement block if CORRECTION, or null",
  "add_to_copilot_pitfalls":     true | false
}}"""


# ── LLM analysis ─────────────────────────────────────────────────────────

def _analyse(observation: str, forced_type: str | None = None,
             provider: str | None = None) -> dict | None:
    """Run LLM analysis on the observation against the headings index of knowledge files.

    Automatically falls back to Ollama if the configured provider fails.
    """
    rules_idx = _extract_headings(_RULES_FILE)
    know_idx  = _extract_headings(_KNOWLEDGE_FILE)

    prompt = _build_analysis_prompt(observation, rules_idx, know_idx, forced_type)
    sys_msg = SystemMessage(content="You are a code-quality analyst. Return only valid JSON, no markdown fences.")

    def _invoke(p: str | None) -> dict | None:
        llm = _make_llm(p)
        try:
            response = llm.invoke([sys_msg, HumanMessage(content=prompt)])
            text = re.sub(r"```json\s*|\s*```", "", response.content.strip()).strip()
            return json.loads(text)
        except json.JSONDecodeError as exc:
            raw = locals().get("response", None)
            print(_err(f"LLM returned invalid JSON: {exc}"))
            if raw:
                print(_info(f"Raw response snippet: {raw.content[:300]}"))
            return None
        except Exception as exc:
            print(_err(f"LLM call failed: {exc}"))
            return None

    result = _invoke(provider)

    # Auto-fallback to Ollama when the user didn't pick a provider explicitly
    # and the configured one failed.
    if result is None and provider is None:
        print(_warn("Primary LLM failed — falling back to Ollama (local)."))
        result = _invoke("ollama")

    return result


# ── File writers ──────────────────────────────────────────────────────────

def _append_rule(analysis: dict) -> None:
    title   = analysis.get("title", "Unnamed Rule")
    section = analysis.get("section", "GENERAL")
    rtype   = analysis.get("rule_type") or "DO"
    body    = analysis.get("body", "")
    bad     = analysis.get("bad_example")
    good    = analysis.get("good_example")
    ts      = datetime.now().isoformat()[:10]

    lines = [f"\n### [{rtype}] {title}"]
    lines.append(f"_Section: {section} | Learned via: learn.py | Date: {ts}_\n")
    lines.append(body)
    if bad:
        lines.append(f"\n```java\n// ❌ WRONG\n{bad}\n```")
    if good:
        lines.append(f"\n```java\n// ✅ CORRECT\n{good}\n```")

    content = "\n".join(lines)
    with _file_lock:
        existing = _read_file(_RULES_FILE)
        if _LEARNED_RULES_HEADER.strip() not in existing:
            _RULES_FILE.write_text(existing + _LEARNED_RULES_HEADER + content, encoding="utf-8")
        else:
            _RULES_FILE.write_text(existing + "\n" + content, encoding="utf-8")


def _append_pattern(analysis: dict) -> None:
    title   = analysis.get("title", "Unnamed Pattern")
    section = analysis.get("section", "GENERAL")
    body    = analysis.get("body", "")
    good    = analysis.get("good_example")
    ts      = datetime.now().isoformat()[:10]

    lines = [f"\n### {title}"]
    lines.append(f"_Section: {section} | Learned via: learn.py | Date: {ts}_\n")
    lines.append(body)
    if good:
        lines.append(f"\n```java\n{good}\n```")

    content = "\n".join(lines)
    with _file_lock:
        existing = _read_file(_KNOWLEDGE_FILE)
        if _LEARNED_PATTERNS_HEADER.strip() not in existing:
            _KNOWLEDGE_FILE.write_text(existing + _LEARNED_PATTERNS_HEADER + content, encoding="utf-8")
        else:
            _KNOWLEDGE_FILE.write_text(existing + "\n" + content, encoding="utf-8")


def _apply_correction(analysis: dict) -> bool:
    """Find and replace the outdated paragraph identified by the LLM."""
    heading   = analysis.get("existing_heading_to_replace")
    new_block = analysis.get("replacement_body")
    if not heading or not new_block:
        print(_warn("CORRECTION verdict but no existing_heading_to_replace — treating as NEW."))
        return False

    # Try in rules file first, then knowledge file
    for path in (_RULES_FILE, _KNOWLEDGE_FILE):
        text = _read_file(path)
        # Find the heading line (stripped of leading ###)
        heading_clean = heading.lstrip("# ").strip()
        pattern = re.compile(
            r"(###[^\n]*" + re.escape(heading_clean) + r"[^\n]*\n)"  # heading line
            r"(.*?)"                                                   # block body
            r"(?=\n###|\Z)",                                           # until next heading or EOF
            re.DOTALL | re.IGNORECASE,
        )
        match = pattern.search(text)
        if match:
            replacement = f"{match.group(1)}{new_block}\n"
            new_text = text[:match.start()] + replacement + text[match.end():]
            with _file_lock:
                path.write_text(new_text, encoding="utf-8")
            print(_ok(f"Corrected section '{heading_clean}' in {path.name}"))
            return True

    print(_warn(f"Heading '{heading}' not found in any knowledge file — treating as NEW."))
    return False


def _append_copilot_pitfall(analysis: dict) -> None:
    """Add to Common Pitfalls section in copilot-instructions.md."""
    if not _COPILOT_FILE.exists():
        print(_warn("copilot-instructions.md not found — skipping pitfall injection."))
        return

    title = analysis.get("title", "Unnamed Pitfall")
    body  = analysis.get("body", "")
    bad   = analysis.get("bad_example")
    good  = analysis.get("good_example")

    # Build a compact bullet-point style entry for the pitfalls list
    bullet = f"- **{title}**: {body}"
    if bad:
        bullet += f"\n  - ❌ `{bad.splitlines()[0]}`"
    if good:
        bullet += f"\n  - ✅ `{good.splitlines()[0]}`"
    bullet += "\n"

    # Find the Common Pitfalls section and append before the next ---/## heading
    text = _read_file(_COPILOT_FILE)
    pitfall_section = re.search(r"(## Common Pitfalls.*?)(\n---|\n##\s)", text, re.DOTALL)
    if not pitfall_section:
        print(_warn("'## Common Pitfalls' section not found in copilot-instructions.md"))
        return

    insert_pos = pitfall_section.end(1)
    new_text = text[:insert_pos] + "\n" + bullet + text[insert_pos:]
    with _file_lock:
        _COPILOT_FILE.write_text(new_text, encoding="utf-8")
    print(_ok(f"Pitfall added to copilot-instructions.md Common Pitfalls"))


def _persist_to_log(observation: str, analysis: dict) -> None:
    """Persist the learning to logs/learnings.jsonl with dedup by title."""
    title_key = analysis.get("title", "").strip().lower()

    existing_titles: set[str] = set()
    if _LEARNINGS_LOG.exists():
        for line in _LEARNINGS_LOG.read_text(encoding="utf-8").splitlines():
            line = line.strip()
            if line:
                try:
                    existing_titles.add(json.loads(line).get("title", "").strip().lower())
                except Exception:
                    pass

    if title_key in existing_titles:
        print(_info(f"Learning '{analysis.get('title')}' already in learnings log — not re-adding."))
        return

    entry = {
        "title":         analysis.get("title"),
        "section":       analysis.get("section"),
        "rule_type":     analysis.get("rule_type"),
        "body":          analysis.get("body"),
        "bad_example":   analysis.get("bad_example"),
        "good_example":  analysis.get("good_example"),
        "source":        "learn.py (manual)",
        "learning_type": analysis.get("learning_type"),
        "observation":   observation,
        "timestamp":     datetime.now().isoformat(),
    }

    _LEARNINGS_LOG.parent.mkdir(parents=True, exist_ok=True)
    with _file_lock:
        with open(_LEARNINGS_LOG, "a", encoding="utf-8") as f:
            f.write(json.dumps(entry, ensure_ascii=False) + "\n")
    print(_ok("Persisted to logs/learnings.jsonl"))


# ── Orchestrator ──────────────────────────────────────────────────────────

def process_observation(observation: str, dry_run: bool = False,
                        forced_type: str | None = None,
                        provider: str | None = None) -> bool:
    """
    Analyse a single observation and apply changes.  Returns True on success.
    """
    observation = observation.strip()
    if not observation:
        print(_err("Empty observation — nothing to do."))
        return False

    print()
    print(_h("─" * 60))
    print(_h("🔍 Analysing observation..."))
    print(_info(f"Observation: {observation[:120]}{'...' if len(observation) > 120 else ''}"))
    print()

    analysis = _analyse(observation, forced_type, provider)
    if not analysis:
        print(_err("Analysis failed — LLM did not return usable output."))
        return False

    # ── Print analysis summary ────────────────────────────────────────────
    verdict  = analysis.get("verdict", "NEW")
    ltype    = analysis.get("learning_type", "RULE")
    title    = analysis.get("title", "")
    ineffective = analysis.get("ineffective", False)
    ineff_reason = analysis.get("ineffective_reason") or ""
    add_pitfall = analysis.get("add_to_copilot_pitfalls", False)

    print(_h(f"Verdict:        {verdict}"))
    print(_h(f"Learning type:  {ltype}"))
    print(_h(f"Title:          {title}"))
    print(_info(f"Body: {(analysis.get('body') or '')[:200]}"))
    if ineff_reason:
        print(_warn(f"Effectiveness: {ineff_reason}"))
    print()

    # ── Early exits ───────────────────────────────────────────────────────
    if ineffective:
        print(_warn(f"Skipped — LLM considers this observation not actionable: {ineff_reason}"))
        return True

    if verdict == "DUPLICATE":
        print(_warn(f"Duplicate — similar content already exists in knowledge files. No changes made."))
        return True

    if dry_run:
        print(_info("Dry-run mode — no files written."))
        print(json.dumps(analysis, indent=2, ensure_ascii=False))
        return True

    # ── Apply changes ─────────────────────────────────────────────────────
    wrote = False

    if verdict == "CORRECTION":
        applied = _apply_correction(analysis)
        if not applied:
            # Fall through to NEW
            verdict = "NEW"

    if verdict == "NEW":
        if ltype in ("RULE", "PITFALL"):
            _append_rule(analysis)
            print(_ok(f"Rule appended to framework_rules.md → '{title}'"))
            wrote = True
        if ltype in ("PATTERN", "PITFALL"):
            _append_pattern(analysis)
            print(_ok(f"Pattern appended to framework_knowledge.md → '{title}'"))
            wrote = True

    if add_pitfall or ltype == "PITFALL":
        _append_copilot_pitfall(analysis)

    if wrote or verdict == "CORRECTION":
        _persist_to_log(observation, analysis)

    print()
    print(_h("─" * 60))
    return True


# ── CLI entry point ───────────────────────────────────────────────────────

def _parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        prog="learn.py",
        description="Feed framework learnings from your observations into the AI pipeline.",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  python learn.py "Select2 options render at body scope, not inside the dialog."
  python learn.py --type RULE "Never call fillInputForAnEntity for checkbox booleans."
  python learn.py --dry-run "preProcess must NOT contain UI test logic."
  python learn.py --file notes.txt
  python learn.py --provider ollama "use Ollama for analysis"
  python learn.py          (interactive — prompts for input)
""",
    )
    parser.add_argument("observation", nargs="?", default=None,
                        help="Observation text (omit for interactive mode)")
    parser.add_argument("--dry-run", action="store_true",
                        help="Analyse only — print result, no file writes")
    parser.add_argument("--type", choices=["RULE", "PATTERN", "PITFALL"], default=None,
                        help="Force learning type (overrides LLM classification)")
    parser.add_argument("--file", default=None, metavar="PATH",
                        help="Ingest each non-empty line in a text file as a separate observation")
    parser.add_argument("--provider", default=None, metavar="PROVIDER",
                        help="Override LLM provider: ollama | openai | openrouter")
    return parser.parse_args()


def main() -> None:
    args = _parse_args()

    # ── File mode ─────────────────────────────────────────────────────────
    if args.file:
        filepath = Path(args.file)
        if not filepath.exists():
            print(_err(f"File not found: {args.file}"))
            sys.exit(1)
        lines = [l.strip() for l in filepath.read_text(encoding="utf-8").splitlines() if l.strip()]
        print(_info(f"Processing {len(lines)} observation(s) from {args.file}"))
        for idx, line in enumerate(lines, 1):
            print(f"\n[{idx}/{len(lines)}]")
            process_observation(line, dry_run=args.dry_run, forced_type=args.type,
                                provider=args.provider)
        return

    # ── Inline arg mode ───────────────────────────────────────────────────
    if args.observation:
        process_observation(args.observation, dry_run=args.dry_run, forced_type=args.type,
                            provider=args.provider)
        return

    # ── Interactive mode ──────────────────────────────────────────────────
    print(_h("learn.py — Interactive Learning Ingestion"))
    print(_info("Type your observation and press Enter. Empty line to quit."))
    print()
    while True:
        try:
            obs = input(f"{_CYAN}> Observation: {_RESET}").strip()
        except (EOFError, KeyboardInterrupt):
            print()
            break
        if not obs:
            break
        process_observation(obs, dry_run=args.dry_run, forced_type=args.type,
                            provider=args.provider)
        print()


if __name__ == "__main__":
    main()
