"""
learning_agent.py
-----------------
Learning Agent: Analyzes batch test results, extracts actionable rules and
patterns using the LLM, updates the framework knowledge files, and drives
a hands-free heal → re-run → learn loop until all tests pass or retries
are exhausted.

What it learns
──────────────
  From FAILURES  → DO / DON'T rules appended to config/framework_rules.md
  From SUCCESSES → Working patterns appended to config/framework_knowledge.md
  All learnings  → persisted to logs/learnings.jsonl (JSONL, one obj/line)

How CoderAgent consumes learnings
──────────────────────────────────
  CoderAgent calls _load_recent_learnings() which reads the JSONL and injects
  the top-N entries as a "Recent Learnings" block in its system prompt.
  This means every future code generation benefits from past execution feedback.

Hands-free loop
───────────────
  1. run_batch → batch_results
  2. LearningAgent.analyze(batch_results) → extract learnings, update files
  3. For each failed result → HealerAgent.heal(result) → patch source
  4. ParallelRunnerAgent.run_batch(failed_configs) → new results
  5. LearningAgent.analyze(new_results) → more learnings
  6. Repeat up to LEARNING_RETRIES times
  7. Final summary stored in state

Pipeline position:
  ... → parallel_runner → learning → [heal_loop?] → END
"""

import json
import re
import threading
from datetime import datetime
from pathlib import Path
from typing import Optional

from langchain_core.messages import SystemMessage, HumanMessage

from agents.state import AgentState
from agents.llm_factory import get_llm
from config.project_config import (
    BASE_DIR,
    DEPS_DIR,
    PROJECT_NAME,
    LEARNINGS_LOG_PATH,
    LEARNING_TOP_N,
    LEARNING_RETRIES,
)


# ── Paths ──────────────────────────────────────────────────────────────────

_RULES_FILE       = Path(BASE_DIR) / "config" / "framework_rules.md"
_KNOWLEDGE_FILE   = Path(BASE_DIR) / "config" / "framework_knowledge.md"
_LEARNINGS_LOG    = Path(LEARNINGS_LOG_PATH)
_LEARNED_RULES_HEADER    = "\n\n---\n\n## LEARNED RULES (auto-generated by LearningAgent)\n"
_LEARNED_PATTERNS_HEADER = "\n\n---\n\n## LEARNED PATTERNS (auto-generated by LearningAgent)\n"

# File-level write lock (protects knowledge files from concurrent writes)
_file_lock = threading.Lock()


# ── Public helper for CoderAgent ──────────────────────────────────────────

def load_recent_learnings(top_n: int = LEARNING_TOP_N) -> str:
    """
    Return the last `top_n` learnings as a formatted string for injection
    into agent prompts.  Returns empty string if no learnings yet.
    """
    if not _LEARNINGS_LOG.exists():
        return ""
    lines = _LEARNINGS_LOG.read_text(encoding="utf-8").strip().splitlines()
    entries = []
    for line in reversed(lines):
        line = line.strip()
        if line:
            try:
                entries.append(json.loads(line))
            except Exception:
                pass
        if len(entries) >= top_n:
            break

    if not entries:
        return ""

    parts = ["=== Recent Learnings from Past Executions ==="]
    for i, e in enumerate(entries, 1):
        ltype = e.get("learning_type", "INFO")
        title = e.get("title", "")
        body  = e.get("body", e.get("description", ""))
        src   = e.get("source", "")
        parts.append(f"{i}. [{ltype}] {title}")
        if body:
            parts.append(f"   {body}")
        if src:
            parts.append(f"   Source: {src}")
    return "\n".join(parts)


# ── Learning Agent ─────────────────────────────────────────────────────────

class LearningAgent:
    """
    Extracts structured learnings from batch run results and feeds them
    back into framework_rules.md, framework_knowledge.md, and
    logs/learnings.jsonl.  Also drives the hands-free heal→re-run loop.
    """

    def __init__(self, base_dir: str = None, deps_dir: str = None):
        self.base     = Path(base_dir) if base_dir else Path(BASE_DIR)
        self.deps_dir = Path(deps_dir) if deps_dir else Path(DEPS_DIR)
        self.llm      = get_llm(temperature=0.1)
        _LEARNINGS_LOG.parent.mkdir(parents=True, exist_ok=True)

    # ── LangGraph node entry point ────────────────────────────────────────

    def run(self, state: AgentState) -> AgentState:
        """
        LangGraph node.

        Reads:   state['batch_run_results'], state['batch_run_configs']
        Writes:  state['learnings'], state['batch_run_results'] (updated after re-runs),
                 state['messages'], state['learning_iteration']
        """
        batch_results = state.get("batch_run_results", [])
        batch_configs = state.get("batch_run_configs") or self._configs_from_results(batch_results)
        iteration     = state.get("learning_iteration", 0)

        if not batch_results:
            state["messages"] = ["[LearningAgent] No batch results to learn from."]
            return state

        print(f"[LearningAgent] 🧠 Analyzing {len(batch_results)} result(s) "
              f"(iteration {iteration + 1})...")

        # ── Extract learnings ─────────────────────────────────────────────
        new_learnings = self.analyze_batch(batch_results)

        # ── Persist & update files ────────────────────────────────────────
        self._persist_learnings(new_learnings)
        rules    = [l for l in new_learnings if l.get("learning_type") == "RULE"]
        patterns = [l for l in new_learnings if l.get("learning_type") == "PATTERN"]
        if rules:
            self._append_to_rules_file(rules)
        if patterns:
            self._append_to_knowledge_file(patterns)

        fails = [r for r in batch_results if not r.get("success", False)]
        print(f"[LearningAgent] Extracted {len(new_learnings)} learnings. "
              f"Failures: {len(fails)}/{len(batch_results)}")

        # ── Hands-free heal + re-run loop ─────────────────────────────────
        final_results = list(batch_results)
        all_learnings = list(new_learnings)

        if fails and iteration < LEARNING_RETRIES:
            print(f"[LearningAgent] 🔄 Hands-free loop: "
                  f"healing {len(fails)} failure(s) and re-running...")
            failed_configs = [
                c for c in batch_configs
                if any(
                    r.get("entity_class") == c.get("entity_class")
                    and r.get("method_name") == c.get("method_name")
                    for r in fails
                )
            ]
            healed_results = self._heal_and_rerun(fails, failed_configs)
            # Merge: replace failed results with new ones
            merged = {(r["entity_class"], r["method_name"]): r for r in final_results}
            for r in healed_results:
                merged[(r["entity_class"], r["method_name"])] = r
            final_results = list(merged.values())

            # Learn from re-run results too
            rerun_learnings = self.analyze_batch(healed_results)
            self._persist_learnings(rerun_learnings)
            all_learnings.extend(rerun_learnings)
            rerun_rules = [l for l in rerun_learnings if l.get("learning_type") == "RULE"]
            rerun_pats  = [l for l in rerun_learnings if l.get("learning_type") == "PATTERN"]
            if rerun_rules:
                self._append_to_rules_file(rerun_rules)
            if rerun_pats:
                self._append_to_knowledge_file(rerun_pats)

        passed = sum(1 for r in final_results if r.get("success"))
        summary = (
            f"[LearningAgent] Final: {passed}/{len(final_results)} passed. "
            f"Learnings extracted: {len(all_learnings)}. "
            f"Rules added: {len([l for l in all_learnings if l.get('learning_type')=='RULE'])}. "
            f"Patterns added: {len([l for l in all_learnings if l.get('learning_type')=='PATTERN'])}."
        )
        print(summary)

        state["learnings"]          = all_learnings
        state["batch_run_results"]  = final_results
        state["learning_iteration"] = iteration + 1
        state["messages"]           = [summary]
        return state

    # ── Core analysis ─────────────────────────────────────────────────────

    def analyze_batch(self, results: list[dict]) -> list[dict]:
        """
        Analyze a list of RunResult dicts and return a list of learning dicts.
        Runs LLM calls concurrently (one per result).
        """
        from concurrent.futures import ThreadPoolExecutor, as_completed as _ac

        learnings = []
        with ThreadPoolExecutor(max_workers=4) as pool:
            futures = {}
            for r in results:
                if r.get("success"):
                    futures[pool.submit(self._extract_success_pattern, r)] = r
                else:
                    futures[pool.submit(self._extract_failure_rule, r)] = r

            for future in _ac(futures):
                result = futures[future]
                try:
                    learning = future.result()
                    if learning:
                        learnings.append(learning)
                except Exception as exc:
                    print(f"[LearningAgent] LLM analysis error for "
                          f"{result.get('entity_class')}.{result.get('method_name')}: {exc}")
        return learnings

    # ── LLM: extract failure rule ─────────────────────────────────────────

    def _extract_failure_rule(self, result: dict) -> Optional[dict]:
        """
        Analyze a failed run result and extract a DO/DON'T rule using the LLM.
        Returns a learning dict or None.
        """
        entity_class    = result.get("entity_class", "?")
        method_name     = result.get("method_name", "?")
        stdout          = result.get("stdout", "")
        stderr          = result.get("stderr", "")
        error           = result.get("error", "")
        product_context = result.get("product_context", {})

        # Read source for context
        source_snippet = self._read_entity_source(entity_class, max_chars=3000)

        # Build human-readable product context block if available
        product_ctx_block = ""
        if product_context:
            product_ctx_block = f"""
PRODUCT CONTEXT (what this test is supposed to do):
  Product Area  : {product_context.get('product_area', '-')}
  Complexity    : {product_context.get('known_complexity', '-')}
  Preprocess    : {product_context.get('preprocess_group', '-')}
  What it tests : {product_context.get('what_it_tests', '-').strip()[:600]}
  Key framework methods exercised:
    {chr(10).join('    - ' + m for m in product_context.get('framework_methods_exercised', [])[:8])}
  Notes         : {product_context.get('note', '-')}
"""

        prompt = f"""You are an expert in the AutomaterSelenium Java test framework for Zoho ServiceDesk Plus.

A test FAILED:
  Entity: {entity_class}
  Method: {method_name}
{product_ctx_block}
ERROR (key lines — noise already filtered):
{self._extract_key_error_lines(stdout + error + stderr)}

FAILING SOURCE CONTEXT:
{source_snippet}

IMPORTANT CONTEXT ABOUT NOISE:
- Lines like `Unable to locate element: //a[@id='zia-decline-button']` or `.tour-skip-all`
  are NORMAL during login — Firefox tries to dismiss optional popups and they often don't exist.
  Do NOT write rules about these locators — they are not test failures.
- `NS_ERROR_NOT_IMPLEMENTED` from BrowserGlue.sys.mjs is a Firefox internal telemetry error, NOT a
  test code issue. Ignore it.
- Only the lines in the ERROR block above are real signal. If the block is empty, the test likely
  timed out or the report was never written — write a rule about that instead.

Analyze the actual ROOT CAUSE and produce ONE actionable, generalisable rule.

Return a JSON object with these EXACT keys:
{{
  "title":        "Short rule title (max 10 words)",
  "section":      "Which framework_rules.md section this belongs to (e.g. SECTION 4 — API CALLS)",
  "rule_type":    "DON'T" or "DO",
  "body":         "Clear, specific explanation of the rule (2-4 sentences). Include the module/product area affected.",
  "bad_example":  "Java code showing the WRONG pattern (single line or null)",
  "good_example": "Java code showing the CORRECT pattern (single line or null)",
  "source":       "{entity_class}.{method_name}"
}}

RULES for your response:
- Focus on the ROOT CAUSE pattern, not the specific test details
- The rule must be GENERALISABLE — applicable to any entity, not just {entity_class}
- If no clear Java-level failure is visible, rule on test environment / timing / preprocess setup
- Return ONLY valid JSON, no markdown"""

        try:
            response = self.llm.invoke([
                SystemMessage(content="You are a Java test automation rule extractor. Return only valid JSON."),
                HumanMessage(content=prompt),
            ])
            text = re.sub(r"```json\s*|\s*```", "", response.content.strip()).strip()
            data = json.loads(text)
            data["learning_type"] = "RULE"
            data["timestamp"]     = datetime.now().isoformat()
            return data
        except Exception as exc:
            print(f"[LearningAgent] Rule extraction LLM error: {exc}")
            return None

    # ── LLM: extract success pattern ─────────────────────────────────────

    def _extract_success_pattern(self, result: dict) -> Optional[dict]:
        """
        Analyze a passing run result and extract a reusable pattern using the LLM.
        Returns a learning dict or None.
        """
        entity_class    = result.get("entity_class", "?")
        method_name     = result.get("method_name", "?")
        product_context = result.get("product_context", {})

        # Read the specific passing method body
        method_body = self._read_method_body(entity_class, method_name)
        if not method_body:
            return None  # nothing useful to analyse

        # Build human-readable product context block if available
        product_ctx_block = ""
        if product_context:
            product_ctx_block = f"""
PRODUCT CONTEXT:
  Product Area   : {product_context.get('product_area', '-')}
  What it tests  : {product_context.get('what_it_tests', '-').strip()[:400]}
  Preprocess Grp : {product_context.get('preprocess_group', '-')}
  Notes          : {product_context.get('note', '-')}
"""

        prompt = f"""You are an expert in the AutomaterSelenium Java test framework for Zoho ServiceDesk Plus.

A test PASSED:
  Entity: {entity_class}
  Method: {method_name}
{product_ctx_block}
PASSING METHOD BODY:
{method_body}

Extract ONE transferable coding pattern that made this test succeed and that other test writers should reuse.
Focus especially on:
- How preProcess sets up test data (API calls, LocalStorage keys)
- How UI interactions are structured (fillInputForAnEntity + manual checkbox clicks)
- How assertions are made (addSuccessReport / addFailureReport patterns)
- How shared locators from other modules are properly reused
- How placeholders like $(custom_X) or $(unique_string) are used safely

Return a JSON object with these EXACT keys:
{{
  "title":        "Short pattern name (max 10 words)",
  "description":  "What this pattern does and why it works (2-3 sentences). Be specific about the framework mechanism.",
  "code_example": "The key Java code block illustrating this pattern (copy from source, max 15 lines)",
  "applies_to":   "Which scenario types benefit from this pattern (1 sentence)",
  "source":       "{entity_class}.{method_name}"
}}

RULES:
- Focus on framework-level patterns (how to call preProcess, how to use LocalStorage,
  how to handle checkboxes, how to validate success messages, etc.)
- Make the title and description generic — not specific to solutions/requests etc.
- Return ONLY valid JSON, no markdown"""

        try:
            response = self.llm.invoke([
                SystemMessage(content="You are a Java test pattern extractor. Return only valid JSON."),
                HumanMessage(content=prompt),
            ])
            text = re.sub(r"```json\s*|\s*```", "", response.content.strip()).strip()
            data = json.loads(text)
            data["learning_type"] = "PATTERN"
            data["timestamp"]     = datetime.now().isoformat()
            return data
        except Exception as exc:
            print(f"[LearningAgent] Pattern extraction LLM error: {exc}")
            return None

    # ── File updaters ─────────────────────────────────────────────────────

    def _append_to_rules_file(self, rules: list[dict]) -> None:
        """Append extracted DO/DON'T rules to framework_rules.md — skips rules
        whose title is already present in the file."""
        existing_md = _RULES_FILE.read_text(encoding="utf-8") if _RULES_FILE.exists() else ""
        lines = []
        skipped = 0
        for r in rules:
            title    = r.get("title", "Unnamed Rule")
            # Skip if this exact title heading already exists in the file
            if f"### " in existing_md and title.lower() in existing_md.lower():
                skipped += 1
                continue
            section  = r.get("section", "GENERAL")
            rtype    = r.get("rule_type", "DO")
            body     = r.get("body", "")
            bad      = r.get("bad_example")
            good     = r.get("good_example")
            src      = r.get("source", "")
            ts       = r.get("timestamp", datetime.now().isoformat())[:10]

            lines.append(f"\n### [{rtype}] {title}")
            lines.append(f"_Section: {section} | Learned from: {src} | Date: {ts}_\n")
            lines.append(body)
            if bad:
                lines.append(f"\n```java\n// ❌ WRONG\n{bad}\n```")
            if good:
                lines.append(f"\n```java\n// ✅ CORRECT\n{good}\n```")
        if skipped:
            print(f"[LearningAgent] ⏭ Skipped {skipped} duplicate rule(s) for framework_rules.md")
        if lines:
            self._write_to_file(_RULES_FILE, _LEARNED_RULES_HEADER, "\n".join(lines))
            print(f"[LearningAgent] ✅ {len(rules) - skipped} new rule(s) appended to framework_rules.md")
        else:
            print(f"[LearningAgent] ℹ All rules already present in framework_rules.md")

    def _append_to_knowledge_file(self, patterns: list[dict]) -> None:
        """Append extracted patterns to framework_knowledge.md — skips patterns
        whose title is already present in the file."""
        existing_md = _KNOWLEDGE_FILE.read_text(encoding="utf-8") if _KNOWLEDGE_FILE.exists() else ""
        lines = []
        skipped = 0
        for p in patterns:
            title   = p.get("title", "Unnamed Pattern")
            # Skip if this exact title heading already exists in the file
            if f"### " in existing_md and title.lower() in existing_md.lower():
                skipped += 1
                continue
            desc    = p.get("description", "")
            code    = p.get("code_example", "")
            applies = p.get("applies_to", "")
            src     = p.get("source", "")
            ts      = p.get("timestamp", datetime.now().isoformat())[:10]

            lines.append(f"\n### {title}")
            lines.append(f"_Learned from: {src} | Date: {ts}_\n")
            lines.append(desc)
            if applies:
                lines.append(f"\n**Applies to:** {applies}")
            if code:
                lines.append(f"\n```java\n{code}\n```")
        if skipped:
            print(f"[LearningAgent] ⏭ Skipped {skipped} duplicate pattern(s) for framework_knowledge.md")
        if lines:
            self._write_to_file(_KNOWLEDGE_FILE, _LEARNED_PATTERNS_HEADER, "\n".join(lines))
            print(f"[LearningAgent] ✅ {len(patterns) - skipped} new pattern(s) appended to framework_knowledge.md")
        else:
            print(f"[LearningAgent] ℹ All patterns already present in framework_knowledge.md")

    def _write_to_file(self, path: Path, section_header: str, content: str) -> None:
        """
        Append content to a knowledge file under a dedicated auto-generated section.
        Thread-safe: uses _file_lock.
        """
        with _file_lock:
            existing = path.read_text(encoding="utf-8") if path.exists() else ""
            if section_header.strip() not in existing:
                # First time — add the section heading
                new_content = existing + section_header + content
            else:
                # Section already exists — append to end of file
                new_content = existing + "\n" + content
            path.write_text(new_content, encoding="utf-8")

    def _persist_learnings(self, learnings: list[dict]) -> None:
        """Append learnings to logs/learnings.jsonl — deduplicates by title to
        prevent the same rule/pattern being logged on every re-run cycle."""
        with _file_lock:
            # Build set of already-known titles from existing log
            existing_titles: set[str] = set()
            if _LEARNINGS_LOG.exists():
                for line in _LEARNINGS_LOG.read_text(encoding="utf-8").splitlines():
                    line = line.strip()
                    if line:
                        try:
                            existing_titles.add(json.loads(line).get("title", "").strip().lower())
                        except Exception:
                            pass

            new_count = 0
            with open(_LEARNINGS_LOG, "a", encoding="utf-8") as f:
                for l in learnings:
                    title_key = l.get("title", "").strip().lower()
                    if title_key and title_key in existing_titles:
                        print(f"[LearningAgent] ⏭ Skipping duplicate learning: '{l.get('title')}'")
                        continue
                    f.write(json.dumps(l, ensure_ascii=False) + "\n")
                    existing_titles.add(title_key)
                    new_count += 1
            if new_count:
                print(f"[LearningAgent] ✅ {new_count} new learning(s) persisted to jsonl")
            else:
                print(f"[LearningAgent] ℹ All learnings were duplicates — nothing new added")

    # ── Hands-free heal + re-run ──────────────────────────────────────────

    def _heal_and_rerun(self, failed_results: list[dict], failed_configs: list[dict]) -> list[dict]:
        """
        For each failed result: invoke HealerAgent, then re-run via ParallelRunnerAgent.
        Returns a list of new RunResult dicts.
        """
        from agents.healer_agent import HealerAgent
        from agents.parallel_runner_agent import ParallelRunnerAgent

        healer = HealerAgent(base_dir=str(self.base), deps_dir=str(self.deps_dir))
        rerun_configs = []

        for result in failed_results:
            entity_class = result.get("entity_class", "")
            method_name  = result.get("method_name", "")
            # Find matching config
            cfg = next(
                (c for c in failed_configs
                 if c.get("entity_class") == entity_class
                 and c.get("method_name") == method_name),
                None,
            )
            if cfg is None:
                continue

            print(f"[LearningAgent] 🩺 Healing: {entity_class}.{method_name}")
            try:
                heal_result = healer.heal_from_run_result(
                    run_result=result,
                    run_config=cfg,
                )
                if heal_result.healed:
                    print(f"[LearningAgent] ✅ Healed — queuing re-run: {method_name}")
                    rerun_configs.append(cfg)
                else:
                    print(f"[LearningAgent] ⚠️  Could not heal {method_name}: {heal_result.error}")
            except Exception as exc:
                print(f"[LearningAgent] Healer error for {method_name}: {exc}")

        if not rerun_configs:
            print("[LearningAgent] No tests were healed — skipping re-run.")
            return failed_results  # return original failed results unchanged

        print(f"[LearningAgent] Re-running {len(rerun_configs)} healed test(s)...")
        runner = ParallelRunnerAgent(base_dir=str(self.base), deps_dir=str(self.deps_dir))
        batch = runner.run_batch(rerun_configs)
        print(batch.summary())
        return batch.to_list()

    # ── Source helpers ────────────────────────────────────────────────────

    def _read_entity_source(self, entity_class: str, max_chars: int = 3000) -> str:
        """Find and return the Base source file for an entity class (trimmed)."""
        src_root = self.base / PROJECT_NAME / "src"
        for candidate in src_root.rglob(f"{entity_class}Base.java"):
            content = candidate.read_text(encoding="utf-8")
            return content[:max_chars]
        for candidate in src_root.rglob(f"{entity_class}.java"):
            content = candidate.read_text(encoding="utf-8")
            return content[:max_chars]
        return ""

    def _read_method_body(self, entity_class: str, method_name: str, max_chars: int = 3000) -> str:
        """
        Extract the body of a specific method from the entity source file.
        Returns empty string if not found.
        """
        source = self._read_entity_source(entity_class, max_chars=50000)
        if not source:
            return ""
        # Find method start — matches `public void methodName(` or `public <type> methodName(`
        pattern = re.compile(
            rf'public\s+\w[\w<>]*\s+{re.escape(method_name)}\s*\(',
        )
        match = pattern.search(source)
        if not match:
            return ""
        start = match.start()
        # Walk forward to find matching closing brace
        depth = 0
        i = start
        while i < len(source):
            if source[i] == '{':
                depth += 1
            elif source[i] == '}':
                depth -= 1
                if depth == 0:
                    return source[start:i + 1][:max_chars]
            i += 1
        return source[start:start + max_chars]

    def _extract_key_error_lines(self, text: str, max_lines: int = 30) -> str:
        """Extract the most relevant error lines from combined output.

        Filters out known noise:
        - Marionette / WebDriver protocol DEBUG lines (Firefox internals)
        - Repeated 404s for benign popup-dismissal probes (zia-decline-button,
          tour-skip-all, dash-enhance-banner) — these appear during every login
          and do NOT indicate test failures
        - Firefox BrowserGlue / NS_ERROR_NOT_IMPLEMENTED telemetry errors
        """
        # Patterns that indicate NOISE (skip these lines)
        _NOISE = [
            "Marionette      DEBUG",
            "Marionette  DEBUG",
            "webdriver::server       DEBUG",
            "webdriver::server  DEBUG",
            "NS_ERROR_NOT_IMPLEMENTED",
            "BrowserGlue.sys.mjs",
            "zia-decline-button",
            "tour-skip-all",
            "tour-skip",
            "dash-enhance-banner",
            "RemoteError@chrome://",
            "WebDriverError@chrome://",
            "dom.find/</<@chrome://",
            "404 Not Found",
        ]
        # Keywords that mark a REAL error
        _SIGNAL = [
            "Exception", "FAILED", "addFailureReport",
            "Caused by", "NoSuchElement", "TimeoutException",
            "NullPointerException", "$$Failure",
            "cannot find symbol", "BUILD FAILED",
            "ClassNotFoundException", "AssertionError",
            "Unable to locate element",
        ]
        relevant = []
        for line in text.splitlines():
            if any(noise in line for noise in _NOISE):
                continue
            if any(kw in line for kw in _SIGNAL):
                relevant.append(line.strip())
        return "\n".join(relevant[:max_lines]) if relevant else text[-1500:]

    def _configs_from_results(self, results: list[dict]) -> list[dict]:
        """Build minimal run_config dicts from RunResult dicts (for re-run)."""
        from config.project_config import SDP_URL, SDP_PORTAL, SDP_ADMIN_EMAIL
        return [
            {
                "entity_class":  r.get("entity_class", ""),
                "method_name":   r.get("method_name", ""),
                "url":           r.get("url", SDP_URL),
                "admin_mail_id": SDP_ADMIN_EMAIL,
                "email_id":      SDP_ADMIN_EMAIL,
                "portal_name":   SDP_PORTAL,
                "skip_compile":  True,
            }
            for r in results
        ]
