module: activities
entity: activity
actions_util:
  file: null
  methods: []
api_util:
  file: null
  methods: []
locators:
  file: com/zoho/automater/selenium/modules/activities/activity/common/ActivityLocators.java
  interfaces:
    ActivityLocators:
    - ALL_MY_ACTVITIES_FILTER
    - CLICK_ACTIVITIES_SUBJECT_WITH_ENTITY_ID
    - GO_TO_DETAILVIEW_AFTER_TEMPLATE_SEARCH
    - CHOOSE_ACTIVITY_TYPE_IN_DROPDOWN
data_constants:
  file: com/zoho/automater/selenium/modules/activities/activity/common/ActivityDataConstants.java
  classes:
    ActivityDataConstants:
    - CREATE_REQUEST_FOR_ACTIVITIES
    - REQUEST_DATA_FOR_GROUP_HEAD
annotation_constants:
  file: null
  groups: []
  data: []
preprocess_groups: []
data_json_keys:
- create_request_for_activities
- request_data_for_group_head
