module: admin
entity: customization_contractmanagement_contractconfiguration
actions_util:
  file: null
  methods: []
api_util:
  file: null
  methods: []
locators:
  file: com/zoho/automater/selenium/modules/admin/customization/contractmanagement/contractconfiguration/common/ContractConfigurationLocators.java
  interfaces:
    ContractConfigurationLocators:
    - SELECTED_TEMPLATE_REMOVE_ICON_IN_CONTRACT_CONF
    - REQUEST_TEMPLATE_CHANGE
data_constants:
  file: null
  classes: {}
annotation_constants:
  file: null
  groups: []
  data: []
preprocess_groups: []
data_json_keys: []
