module: admin
entity: instanceconfigurations_region
actions_util:
  file: null
  methods: []
api_util:
  file: null
  methods: []
locators:
  file: com/zoho/automater/selenium/modules/admin/instanceconfigurations/region/common/RegionLocators.java
  interfaces:
    RegionLocators: []
data_constants:
  file: null
  classes: {}
annotation_constants:
  file: null
  groups: []
  data: []
preprocess_groups: []
data_json_keys: []
