module: admin
entity: templatesandforms_incidenttemplate
actions_util:
  file: null
  methods: []
api_util:
  file: null
  methods: []
locators:
  file: com/zoho/automater/selenium/modules/admin/templatesandforms/incidenttemplate/common/IncidentTemplateLocators.java
  interfaces:
    IncidentTemplateLocators:
    - TABLE_MENU
    - SEARCH_INPUT_IN_REPORT_AN_ISSUE
    - TYPE_INPUT
    - CLICK_TEMP_NAME_IN_REQUESTER
    - SELECT_TEMPLATE_FROM_LISTVIEW
    - VERIFY_TITLE
    Editor:
    - SEARCH_FIELDS_TEMPLATE
    - TEMPLATE_NAME
    - SAVE_BUTTON
    - REQUESTER_FIELD
    - GET_TEMPLATE_NAME
    - DEFAULT_TEMPLATE
    - CLICK_SETTINGS_ICON_FOR_UDF_FIELDS
    - DATA_FIELD_REF_NAME
    - CLICK_FIELD_PROPERTIES_IN_SETTINGS
    - VERIFY_UDF_IS_MANDATORY
    - CLICK_TEMPLATE_USING_ENTITY_ID
    - CLICK_TEMPLATE_USING_NAME
    - BACK_BUTTON_LOCATOR
    - MAKE_DEFAULT_TEMPLATE_USING_NAME
    - VERIFY_IT_IS_DEFAULT_TEMPLATE
    - SETTINGS_ICON_USING_TEMPLATE_NAME
    - INACTIVE_CUSTOMER_NOT_PERMIT_LOCATOR
    - UPDATE_UDF
    - ATTACH
    - VERIFY_ATTACHMENT_IMAGE
    - COMMENTS
    - ACTION_OPTION
    - FIELDS_PRESENT
    - CI_FIELD
    - FIELD_NAME_TITLE
    Popup:
    - TEMPLATE_TYPE
    - SELECT_SERVICE_CATEGORY
    Helpcard:
    - FORM_CUSTOMIZATION
    - HELPCARD_CONTENT
    - REQUEST_FORM
    - REQUEST_DETAILS_PAGE
    - COPY_HELPCARD_TO_REQUESTER_VIEW
    - VERIFY_CONTENT
    - ATTACHMENT
    - ATTACHMENT_PLUS_ICON
    - HELPCARD_REQUEST
    - HELPCARD_CARD_DETAILS
data_constants:
  file: com/zoho/automater/selenium/modules/admin/templatesandforms/incidenttemplate/common/IncidentTemplateDataConstants.java
  classes:
    IncidentTemplateDataConstants:
    - INCIDENT_TEMPLATE_WITH_REQ_HELPCARD
    - COPY_TEMPLATE_LASTUPDATEDBY_SERVICETOINCIDENT
    - INCIDENT_TEMPLATE_WITH_ALL_TYPE_UDF
    - REQUEST_TEMPLATE
    - CREATE_INCIDENTREQUEST_TEMPLATE_WITH_LOOKUP_FIELD
    - COPY_TEMPLATE_LASTUPDATEDBY
    - INCIDENT_TEMPLATES_WITH_ALL_UDF_DATA
    - INCIDENT_TEMPLATE_WORKFLOW_ASSOCIATION
    - COPY_TEMPLATE
    - CREATE_INCIDENT_TEMPLATE_VIA_API_WITH_ALL_RHS_FIELDS
    - LIST_INFO_FIELD_KEY_NAME_SEARCH
    - INCIDENT_TEMPLATE_WITH_HELPCARD_FORM_ENABLED
    - INCIDENT_TEMPLATE_WITH_HELPCARD
    - INCIDENT_TEMPLATE_WITH_EMPTY_HELPCARD
    - COPY_TEMPLATE_LASTUPDATEDBY_SERVICE
    - CUSTOMIZED_IR_TEMPLATE_FOR_CMDB
    - REMOVE_CI_FIELD_REQUEST_TEMPLATE
    - SERVICE_TEMPLATES_WITH_ALL_UDF_DATA
    - COPY_TEMPLATE_LASTUPDATEDBY_INCIDENTTOSERVICE
    - TASK_ASSOCIATE_TEMPLATE
    - INCIDENT_TEMPLATE_WITH_WORKFLOW
    - ASSOCIATE_REQUEST_FIELDS_FOR_TASK
    - INCIDENT_TEMPLATE_WITH_REQ_HELPCARD_FORM_ENABLED
    - INCIDENT_TEMPLATE_WITH_SITELOOKUP_AND_EMAILID
    - INCIDENT_TEMPLATE_WITH_LOOKUP_FIELD_REQUESTER_CAN_SET_AND_VIEW_FALSE
    - INCIDENT_TEMPLATE_WITH_SERVICE_CATEGORY
    - UPDATE_SERVICE_CATEGORY_VALUES
annotation_constants:
  file: null
  groups: []
  data: []
preprocess_groups: []
data_json_keys: []
