module: cmdb
entity: cmdb
actions_util:
  file: null
  methods: []
api_util:
  file: com/zoho/automater/selenium/modules/cmdb/cmdb/utils/CmdbAPIUtil.java
  methods:
  - name: createCmdbWithDefault
    return_type: void
    params: String cmdbData, String cmdbTypes
    purpose: without creating CI
  - name: formatTypeName
    return_type: String
    params: String input
    purpose: ''
  - name: createCmdb
    return_type: void
    params: String cmdbData
    purpose: ''
  - name: createDowntime
    return_type: void
    params: String downtimeData
    purpose: ''
  - name: createRelationshipsInCI
    return_type: void
    params: String inputData, String path
    purpose: ''
  - name: createRelationship
    return_type: void
    params: String parentCitype, String targetCitype
    purpose: ''
  - name: addSuggestedRelationship
    return_type: void
    params: String parentEntityId, String targetEntityId, String relationshipId, String parentname
    purpose: ''
  - name: addCustomRelationship
    return_type: void
    params: String parentapiname, String parentCITypeId, String targetCIEntityId, String targetcitypeID
    purpose: Store it using LocalStorage
  - name: createMultipleCmdbWithDefault
    return_type: void
    params: String cmdbData, String cmdbTypes, int noofCI
    purpose: without creating CI
  - name: getCIIDUsingName
    return_type: String
    params: String ciName
    purpose: ''
locators:
  file: com/zoho/automater/selenium/modules/cmdb/cmdb/common/CmdbLocators.java
  interfaces:
    CmdbLocators:
    - INPUT_ACCORDION_SEARCH
    - SPAN_ACCORDION_SEARCH_RESULT
    - CMDB_CITYPE_SEARCH_RESULT
    - CLICK_ROW_ACTIONS_WITH_ENTITYID
    - CLICK_FROM_ROW_ACTIONS
    - SELECT_CHECKBOX_USING_CMDBNAME
    - EMPTY_CI
    - GETENTITYID_FROM_FIRSTROW
    - TOP_MENU_BAR
    - TABLE_HEADER
    - HEADING_NAME_IN_LISTVIEW
    - NO_CONFIGURATION_ITEM_IS_AVAILABLE
    - SHOW_TOTAL_COUNT
    - TOTAL_COUNT_IN_RHS
    - COLUMN_HEADING_NAME
    - FIRST_ROW_IN_LISTVIEW
    - EMPTY_MSG_IN_LISTVIEW
    - ICON_CLEAR_SEARCH
    - COLUMN_SEARCH
    - SELECTED_ROW_COUNT_HEADER_IN_SELECT_ITEMS
    - SEARCHED_ROW_CHECKBOX_MARK_CI
    - GRANT_ACCESS_LOCATOR
    - CMDB_CITYPE
    - GET_INTERNAL_NAME
    - SELECT_CMDB_IN_LHS
    - BUSINESS_VIEW
    - FILTER_DROPDOWN
    - DELETE_CUSTOMFILTER
    - EDIT_CUSTOMFILTER
    - HISTORY_FILTER
    - GET_UDF_INTERNAL_NAME
    - CI_LIST
    - MODIFY_CITYPE
    - SELECT_CITYPE
    - SELECTCI
    - MODIFY
    - VERIFY_CI_TITLE
    - SELECT_CI_BY_TITLE
    - VERIFYMODIFYCI
    - CANCEL_MODIFYCI
    - ALERT_LOCATOR
    - MODIFY_CITYPE_FROM_ACTIONS
    - DATA_WITH_ROW_ID
    Detailview:
    - DETAILVIEW_TOP_MENU_BAR
    - GOBACK_BUTTON_LOCATOR
    - HORIZONTAL_OR_VERTICAL_BUTTON
    - ZOOM_BUTTON_IN_RELATIONSHIP_MAP
    - SAVE_AS_BUSINESSVIEW_OR_VIEWDETAILS
    - MANDATORY_FIELD_ERROR_MESSAGE
    - HORIZONATL_VERTICAL_FORCE_BUTTON_IN_RELATIONSHIP_MAP
    - ZOOM_OUT_BUTTON_IN_RELATIONSHIP_MAP
    - LINK_THIS_CI_DETAILVIEW
    - DELETE_LINK_THIS_CI
    - DETAILVIEW_ACTIONS_DROPDOWN
    - DEMO
    - NO_OF_COPIES_TEXT_FIELD
    - CI_PERFORMED_BY
    - CREATED_CI_LOGS_IN_HISTORY
    - HISTORY_OPERATION
    - PERFORMED_BY
    - STATUS_COMMENT
    - RELATIONSHIP_MAP_PAGE
    - RELATIONSHIPS_SUBTAB_IN_DETAILVIEW
    - NO_MATCHES_FOUND
    - COLUMN_SEARCH_IN_CMDB_ASSOCIATION_SUBTAB
    - HEADER
    - SEARCH_TABLE_HEADER
    - EMPTY_ASSOCIATON_TABLE
    - GO_BUTTON_IN_ASSOCIATONS_TABLE
    - FILL_EMAIL_NAME
    - AVAILABLE_FIELDS_IN_CI
    - HOVER_FIELD_NAME
    - MDDIFY_TEMPLATE_USING_DISPLAYNAME
    - MDDIFY_TEMPLATE_USING_DISPLAYNAME
    - IS_ELEMENT_VISIBLE
    - DESCRIPTION
    - BUSINESS_VIEW_DETAILS
    - SELECT_SOURCE
    - SELECT_DESTINATION
    - SELECT_SOURCE_AND_DESTINATION
    - POPUP_RHS_SEARCH_BOX
    - RELATIONSHIPS_TYPE_IN_ADD_RELATIONSHIP
    - SELECT_CHECKBOX_IN_POPUP
    - SELECT_CHECKBOX_IN_REL_POPUP
    - RELATIONSHIP_NAME
    - ADD_BUTTON_IN_POPUP
    - ADDED_CMDB_NAME_IN_RELATIONSHIPS_SUBTAB
    - SOURCE_CI_NAME_IN_RELATIONSHIP_SUBTAB_POPUP
    - POPUP_GO_BUTTON
    - CHECKBOX_IN_POPUP
    - MANDATORY_FIELD_SYMBOL
    - MANDATORY_FIELD_ERROR_MESSAGE_IN_POPUP
    - NO_MATCHES_FOUND_IN_DROPDOWN
    - SELECT_RADIOBOX_IN_POPUP
    - PREVIOUS_BUTTON_IS_INACTIVE
    - POPUP_TITLE
    - SELECT_MODULE_IN_POPUP
    - CLOSE_BUTTON_IN_POPUP
    - LINK_THIS_CI
    - SELECT_TEMPLATE_IN_POPUP
    - POPUP_HEADING_NAME
    - NUMBER_OF_COPIES
    - NO_OF_COPIES_ERROR_MSG
    - IS_POPUP_PRESENT
    - EMPTY_DATA
    - IS_PREVIOUS_BUTTON_ENABLE
    - GETENTITYID_FROM_POPUP_FIRSTROW
    - GETNAME_FROM_POPUP_FIRSTROW
    - FIRST_ROW_TEXT_VERIFY
    - UDF_FIELD_IN_TEMPLATE
    - UDF_FIELD_IN_CI_TEMPLATE
    - UDF_FIELD_IN_AVAILABLE_TEMPLATE
    - UDF_FIELD_IN_AVAILABLE_CI_TEMPLATE
    - AJAX_MSG
    - SAVE_BUTTON_IN_POPUP
    - HOVER_FIELDNAME
    - SELECT_DESTINATION_CI_TYPE
    - HEADER1
    - NO_HISTORY_AVAILABLE
    - HISTORY_UPDATATION
    - CI_DOWNTIME_DETAILS
    - CI_DOWNTIME
    - DOWNTIME_LISTVIEW
    - DOWNTIME_FIELDS
    - CIS_INVOLVED_FIELD
    - REMOVE_OPTION_CIS_INVOLVED_FIELD
    - SEARCH_CIS_INVOLVED
    - CIS_INVOLVED_POPUP
    - POPUP_TABLE_SETTING
    - POPUP_ACK_FUNCTION
    - CIS_INVOLVED_FIELD_LIST
    - CIS_SELECTED_LINK
    - CIS_SELECTED_LINK_POPUP
    - SETUP_ACTION_LIST
    - GET_SCHEDULED_START_VALUE
    - DOWNTIME_RHS
    - DOWNTIME_RHS_VALUE
    - DOWNTIME_FILTER
    - RELEASE_DOWNTIME_EDIT
    - BUSINESS_VIEWS
    - BASE_CI
    - BASE_CI_IN_BUSINESS_VIEW
    - BUSINESS_VIEW_SAVE
    - BUSINESS_VIEW_DOWNTIME_COUNT
    - BUSINESS_VIEW_COUNT
    - DOWNTIME_SUMMARY_POPUP
    - TIME_FILTER_LIST
    - TIME_FILTER
    - NOTIFICATION_CONTENT
    - NOTIFICATION_EDIT
    - ORIGIN_LINK
    - LISTVIEW_TIME_FILTER
    - CIS_INVOLVED_LIST
    - SUGGESTED_RELATIONSHIP
    - DETAILS_INFO
    - DETAILS_PAGE_FIELDS
    - NAVIGATE_SUBTAB
    - RELATIONSHIP_MAP_ENTITY
    - RELATIONSHIPS_TAB_LISTVIEW
    - RELATIONSHIPS_TAB_TEMPLATEVIEW
    - RELATIONSHIPMAP_SAVE
    - BUSINESS_VIEWS_CHECKBOX
    - CHECKBOX_BULK
    - NO_DATA_AVAILABLE
    - BUSINESS_VIEW_RELATIONSHIP_MAP
    - CIS_INVOLVED_FIELD_DATA
    - FIELD_LOCATOR_BY_TITLE
    - VERIFY_RELATIONSHIPTYPE
    - CI_HISTORY_UPDATED
    - HISTORY_DATA
    - UDF_FIELD_VERIFY
    - VERIFY_SCHEDULED_DOWNTIMES
    - VERIFY_REQUEST_SUBJECT_IN_ASSOCIATIONS
    - SUBTAB_HEADERS
    - CI_FORM_FIELD_VALUE
    - ACKNOWLEDGEMENT_BUTTON
    - APPLIES_TO_FIELD_IN_LINKCI
    - SAVEORCANCELBUTTON_IN_RELATIONSHIPMP
    - RELATIONSHIPMAP_ACTIONS
    - RELATIONSHIPMAPACIONS_BUTTON
    ValidationMessage:
    - VERIFY_VALIDATION_MESSAGE
    CommonLocators:
    - MULTI_SELECT_SEARCH_INPUT
    - CI_TYPE_OPTION_ELEMENT
data_constants:
  file: com/zoho/automater/selenium/modules/cmdb/cmdb/common/CmdbDataConstants.java
  classes:
    CmdbDataConstants:
    - DOWNTIME_SUMMARY_TIMEFILTER
    - CREATE_DOCUMENT
    - DOWNTIME_API
    - HISTORYTABSOPERATIONS
    - ADD_CMDB
    - EDIT_UDF_IN_UI
    - SEARCH_CHANGE_STAGE
    - CREATE_APPLICATION
    - CMDB_VIEW_CRITERIA_WITH_DYNAMIC_LOOKUP_REPORTING_TO
    - CREATE_SWITCH_NETWORK_GEAR
    - GET_ENTITYID
    - CREATE_CUSTOMCONTRACTTEMPLATE_WITH_CI
    - CREATE_CMDB_FOR_IMPORT
    - UPDATE_IBM_WORKSTATION
    - DOWNTIME_SEARCH_FIELDS
    - CREATE_COMPUTER
    - UPDATE_NETWORK_GEAR
    - CREATE_BUSINESS_VIEW
    - UPDATE_PEOPLE
    - CREATE_CI_WITH_CMDB_FIELDS
    - SUGGEST_RELATIONSHIP
    - CREATE_PEOPLE
    - UPDATE_AIX_WORKSTATION
    - CMDB_CREATE_WITH_LOOKUP_FIELD_VALUE
    - SEARCH_CRITERIA_FOR_CORPORATE_WEBSITE
    - SEARCH_DATA
    - CREATE_EOL_STATE_CI
    - CREATE_CUSTOM_CI
    - ADD_CMDB_USING_APPLICATION
    - CREATE_CI_WITH_ALL_FIELDS
    - SEARCH_CRITERIA_FOR_CUSTOM_CI
    - SEARCH_RELATIONSHIP_ID
    - ADD_CMDB_FOR_NR
    - CREATE_CMDB
    - UPDATE_SUPPORT_GROUP
    - CMDB_VIEW_CRITERIA_WITH_NULL_VALUE_IMPORT
    - UPDATE_FIREWALL_NETWORK_GEAR
    - CREATE_APPLICATION_IN_UI
    - CREATE_TEAM
    - CREATE_ACTIVE_STATE_CI
    - UPDATE_RACK
    - COPY_CI
    - DOWNTIME_RHS
    - ASSOCIATED_GROUP
    - DOWNTIME_LISTVIEW_FIELDS
    - SEARCH_CITYPE_ID
    - CREATE_CONTRACT_IN_UI
    - UPDATE_UNIX_WORKSTATION
    - SEARCH_CRITERIA_FOR_REQUEST_A_CRMACCOUNT
    - SET_TABLE_SETTING
    - CREATE_APACHE_INSTANCE
    - DOWNTIME_API_2
    - DOWNTIME_API_1
    - DOWNTIME_API_3
    - CREATE_CI_IN_UI
    - EDIT_CUSTOM_VIEW_WITH_ONECRITERIA
    - CREATE_HPUX_WORKSTATION
    - CREATE_SERVICE
    - GET_BUSINESS_IMPACT_ID
    - UPDATE_HPUX_WORKSTATION
    - GET_PERSONALIZATION
    - CMDB_VIEW_CRITERIA_WITH_DYNAMIC_USER_LOOKUP
    - CREATE_ACCESS_POINT_NETWORK_GEAR
    - ADD_RELATIONSHIPS
    - ADD_CMDB_USING_ACCESSPOINT
    - SUGGESTED_RELATIONSHIPS
    - DOWNTIME_PERSONALIZATION
    - CREATE_CHANGE
    - CREATE_RACK
    - UPDATE_DATA
    - CREATE_UNIX_WORKSTATION
    - CREATE_FIREWALL_NETWORK_GEAR
    - CREATE_VIRTUAL_HOST_ASSET
    - CREATE_LOOKUP_IN_UI
    - CREATE_IBM_WORKSTATION
    - CREATE_DATA_CENTER
    - UPDATE_ROUTER_NETWORK_GEAR
    - UPDATE_TEAM
    - DOWNTIME_FIELDS
    - UPDATE_COMPUTER
    - CREATE_AIX_WORKSTATION
    - CUSTOM_RELATIONSHIP
    - UPDATE_DATA_CENTER
    - SEARCH_CRITERIA
    - CMDB_DEFAULT_NOTIFICATION
    - CREATE_LOOKUP_VIA_API
    - CREATE_DOWNTIME_WITH_FULL_DATA
    - MODIFY_CI_TYPE_DATA
    - CREATE_SUPPORT_GROUP
    - REQUEST_VALID_INPUT_UI
    - CREATE_APPLICATION_CI_TEMPLATE
    - CREATE_NETWORK_GEAR
    - CUSTOM_CI_TYPE
    - UPDATE_ACCESS_POINT_NETWORK_GEAR
    - DEMOSS
    - CREATE_ROUTER_NETWORK_GEAR
    - UPDATE_SERVICE
    - CUSTOM_VIEW_WITH_ONECRITERIA
    - UPDATE_SWITCH_NETWORK_GEAR
    - MODIFY_DATACENTER_TEMPLATE
    - CREATE_REGION
    - CREATE_DOWNTIME_2
    - COLUMN_CHOOSER_LISTVIEW
    - RELATIONSHIP_IN_CI
    - CREATE_VIRTUAL_MACHINE_ASSET
    - ASSOCIATED_CUSTOM_SITE
    - UPDATE_DOCUMENT
annotation_constants:
  file: null
  groups: []
  data: []
preprocess_groups: []
data_json_keys:
- Column_Chooser_Listview
- Copy_CI
- Custom_View_With_OneCriteria
- Edit_Custom_View_With_OneCriteria
- HistoryTabsOperations
- Relationship_in_CI
- Request_Valid_Input_UI
- Search_citype_id
- Search_relationship_id
- add_cmdb
- add_cmdb_for_NR
- add_cmdb_using_accesspoint
- add_cmdb_using_application
- add_relationships
- associated_custom_site
- associated_group
- cmdb_create_with_lookup_field_value
- cmdb_default_notification
- cmdb_view_criteria_with_dynamic_lookup_reporting_to
- cmdb_view_criteria_with_dynamic_user_lookup
- cmdb_view_criteria_with_null_value_import
- create_Application_CI_template
- create_CI_with_all_fields
- create_CustomcontractTemplate_with_CI
- create_access_point_network_gear
- create_active_state_ci
- create_aix_workstation
- create_apache_instance
- create_application
- create_application_in_ui
- create_business_view
- create_change
- create_ci_in_ui
- create_ci_with_cmdb_fields
- create_cmdb
- create_cmdb_for_import
- create_computer
- create_contract_in_UI
- create_custom_ci
- create_data_center
- create_document
- create_downtime_2
- create_downtime_with_full_data
- create_eol_state_ci
- create_firewall_network_gear
- create_hpux_workstation
- create_ibm_workstation
- create_lookup_in_UI
- create_lookup_via_api
- create_network_gear
- create_people
- create_rack
- create_region
- create_router_network_gear
- create_service
- create_support_group
- create_switch_network_gear
- create_team
- create_unix_workstation
- create_virtual_host_asset
- create_virtual_machine_asset
- custom_ci_type
- custom_relationship
- demoss
- downtime_api
- downtime_api_1
- downtime_api_2
- downtime_api_3
- downtime_fields
- downtime_listview_fields
- downtime_personalization
- downtime_rhs
- downtime_search_fields
- downtime_summary_timefilter
- edit_udf_in_UI
- 'get_business_impact_id '
- get_entityid
- get_personalization
- modify_ci_type_data
- modify_datacenter_template
- search_change_stage
- search_criteria
- search_criteria_for_corporate_website
- search_criteria_for_custom_ci
- search_criteria_for_request_a_CRMaccount
- search_data
- set_table_setting
- suggest_relationship
- suggested_relationships
- update_access_point_network_gear
- update_aix_workstation
- update_computer
- update_data
- update_data_center
- update_document
- update_firewall_network_gear
- update_hpux_workstation
- update_ibm_workstation
- update_network_gear
- update_people
- update_rack
- update_router_network_gear
- update_service
- update_support_group
- update_switch_network_gear
- update_team
- update_unix_workstation
