module: customers
entity: customer
actions_util:
  file: null
  methods: []
api_util:
  file: null
  methods: []
locators:
  file: com/zoho/automater/selenium/modules/customers/customer/common/CustomerLocators.java
  interfaces:
    CustomerLocators:
    - CUSTOM_VIEW_NAME_INPUT
    - CUSTOM_VIEW_COLUMN_CHOOSE_LOCATOR
    - CUSTOM_VIEW_CRITERIA_VALUE_INPUT
    - CUSTOM_VIEW_SAVE_BUTTON
    - CLICK_CUSTOMER_USING_NAME
    - CUSTOMER_ICON
    - CUSTOMER_SETTINGS_ICON
    - CUSTOM_VIEW_NAME
    - INACTIVE_CUSTOMER_NAME
    - CUSTOMER_ANNOUNCEMENT_SETTING_ICON
    Detailview:
    - RHS_ASSOCIATIONCOUNT
data_constants:
  file: com/zoho/automater/selenium/modules/customers/customer/common/CustomerDataConstants.java
  classes:
    CustomerDataConstants:
    - CREATE_CUSTOMER
    - CREATE_CUSTOMER_USING_OTHER_CUSTOMER_SITE_NAME
annotation_constants:
  file: null
  groups: []
  data: []
preprocess_groups: []
data_json_keys:
- create_customer
- create_customer_using_other_customer_site_name
