module: general
entity: downtime
actions_util:
  file: null
  methods: []
api_util:
  file: null
  methods: []
locators:
  file: com/zoho/automater/selenium/modules/general/downtime/common/DowntimeLocators.java
  interfaces:
    DowntimeLocators: []
data_constants:
  file: com/zoho/automater/selenium/modules/general/downtime/common/DowntimeDataConstants.java
  classes:
    DowntimeDataConstants:
    - DOWNTIME_API
annotation_constants:
  file: null
  groups: []
  data: []
preprocess_groups: []
data_json_keys:
- downtime_api
