module: general
entity: techavailabilitychart
actions_util:
  file: null
  methods: []
api_util:
  file: null
  methods: []
locators:
  file: com/zoho/automater/selenium/modules/general/techavailabilitychart/common/TechAvailabilityChartLocators.java
  interfaces:
    TechAvailabilityChartLocators:
    - DATE
    - UNAVAILABILITY_TYPE
    - LEAVEID
    - LOAD_MORE
    - TYPE
    - ALL_TECH_DROP_DOWN
    - POPUP_SAVE_CANCEL_BUTTONS
    - TECH_INFO_ICON
    - COPY_ICON
    - TECH_DETAILS_SECTION
    - TECH_INFO_DETAILS
    - NEW_DELEGATION
    - REQUESTER_ACTIVE_DELEGATION
    - LEAVE_TYPE_IN_HEADDER
    - NO_COLOR_UNAVAILABILITY
    - UNAVAILABILITY_EDIT
    - UNAVAILABBLE_CLOSE
    - SCHEDULAR_TECH_SELECT
    - REQUESTER_SELECT_FIELD_DELEGATION
    - SCHEDULAR_UNAVAILABILITY
    - TECH_AVAILABILITY_CHART_UNAVAILABILITY
    - TECHNICIAN_JOB_TITLE
data_constants:
  file: com/zoho/automater/selenium/modules/general/techavailabilitychart/common/TechAvailabilityChartDataConstants.java
  classes:
    TechAvailabilityChartDataConstants:
    - UNAVAILABILITY_API_DATA
    - UNAVAILABILITY_API_DATA_REQUESTER
annotation_constants:
  file: null
  groups: []
  data: []
preprocess_groups:
- name: Create_requester_enable_delegation
  creates_count: 0
  local_storage_keys:
  - UserId
  - UserDisplayId
- name: Create_technician_with_job_title
  creates_count: 0
  local_storage_keys: []
data_json_keys: []
