module: general
entity: worklog
actions_util:
  file: null
  methods: []
api_util:
  file: com/zoho/automater/selenium/modules/general/worklog/utils/WorklogAPIUtil.java
  methods:
  - name: createWorklog
    return_type: String
    params: TestCaseData worklogdata
    purpose: ''
  - name: worklogCreationInRequest
    return_type: Map<String, JSONObject>
    params: TestCaseData worklogdata
    purpose: ''
  - name: worklogCreationInProblem
    return_type: Map<String, JSONObject>
    params: TestCaseData worklogdata
    purpose: ''
  - name: worklogCreationInChange
    return_type: Map<String, JSONObject>
    params: TestCaseData worklogdata
    purpose: ''
  - name: worklogCreationInRelease
    return_type: Map<String, JSONObject>
    params: TestCaseData worklogdata
    purpose: ''
  - name: worklogCreationInProject
    return_type: Map<String, JSONObject>
    params: TestCaseData worklogdata
    purpose: ''
  - name: worklogCreationInRequestsTask
    return_type: Map<String, JSONObject>
    params: TestCaseData taskData, TestCaseData worklogdata
    purpose: ''
  - name: worklogCreationInProblemTask
    return_type: Map<String, JSONObject>
    params: TestCaseData taskData, TestCaseData worklogdata
    purpose: ''
  - name: worklogCreationInProjectTask
    return_type: Map<String, JSONObject>
    params: TestCaseData taskData, TestCaseData worklogdata
    purpose: ''
  - name: worklogCreationInChangeTask
    return_type: Map<String, JSONObject>
    params: TestCaseData taskData, TestCaseData worklogdata
    purpose: ''
  - name: worklogCreationInReleaseTask
    return_type: Map<String, JSONObject>
    params: TestCaseData taskData, TestCaseData worklogdata
    purpose: ''
  - name: worklogCreationInGeneralTask
    return_type: Map<String, JSONObject>
    params: TestCaseData taskData, TestCaseData worklogdata
    purpose: ''
  - name: editWorklogInRequest
    return_type: Map<String, JSONObject>
    params: TestCaseData worklogdata
    purpose: ''
  - name: editWorklogInProblem
    return_type: Map<String, JSONObject>
    params: TestCaseData worklogdata
    purpose: ''
  - name: editWorklogInProject
    return_type: Map<String, JSONObject>
    params: TestCaseData worklogdata
    purpose: ''
  - name: editWorklogInChange
    return_type: Map<String, JSONObject>
    params: TestCaseData worklogdata
    purpose: ''
  - name: editWorklogInRelease
    return_type: Map<String, JSONObject>
    params: TestCaseData worklogdata
    purpose: ''
  - name: editWorklogInGeneral
    return_type: Map<String, JSONObject>
    params: TestCaseData worklogdata
    purpose: ''
locators:
  file: com/zoho/automater/selenium/modules/general/worklog/common/WorklogLocators.java
  interfaces:
    WorklogLocators:
    - EDIT_DELETE_WORLOG
    - DESCRIPTION_SEARCH
    - HOVER_WORKLOG
    - TEXT_UNDER_NOTE
    - EDIT_WORKLOG
    - ADD_WORKLOG_IN_RESOLUTION_TAB
    - CLICK_TECH_TIME_ELAPSED_ANALYSIS
    - ADD_WORKLOG_IN_TIMEELAPSED_ANALYSIS
    - GET_FIELDVALUE_FROM_WORKLOG
    - CLICK_DROPDOWN
data_constants:
  file: com/zoho/automater/selenium/modules/general/worklog/common/WorklogDataConstants.java
  classes:
    WorklogDataConstants:
    - API_WORKLOG1
    - UI_WORKLOG1_EDITDATA
    - API_WORKLOG2
    - UI_WORKLOG1
    - WOKLOG_FOR_PROJECT
    - WOKLOG_FOR_MULTICURRENCY
annotation_constants:
  file: null
  groups: []
  data: []
preprocess_groups: []
data_json_keys:
- API_Worklog1
- API_Worklog2
- UI_Worklog1
- UI_Worklog1_EditData
- Woklog_for_multicurrency
- Woklog_for_project
