module: general
entity: downtime
actions_util:
  file: null
  methods: []
api_util:
  file: null
  methods: []
locators:
  file: null
  interfaces: {}
data_constants:
  file: com/zoho/automater/selenium/modules/general/downtime/common/DowntimeDataConstants.java
  classes:
    DowntimeDataConstants:
    - DOWNTIME_API
annotation_constants:
  file: null
  groups: []
  data: []
preprocess_groups: []
data_json_keys:
- downtime_api
data_json_deep:
  total_entries: 1
  field_frequency:
    downtime: 1
  all_placeholders:
  - datetime, 0Y 0M 0D 0h 0m, true
  - datetime, 0Y 0M 0D 0h 20m, true
  - unique_string
  reuse_groups_count: 0
  entries:
    downtime_api:
      fields:
      - downtime
      placeholders:
      - unique_string
      - datetime, 0Y 0M 0D 0h 0m, true
      - datetime, 0Y 0M 0D 0h 20m, true
      local_storage_keys_required: []
      purpose: ui_form
