module: maintenance
entity: requestmaintenance
actions_util:
  file: null
  methods: []
api_util:
  file: null
  methods: []
locators:
  file: com/zoho/automater/selenium/modules/maintenance/requestmaintenance/common/RequestMaintenanceLocators.java
  interfaces:
    RequestMaintenanceLocators:
    - CHECKBOX_LISTVIEW
    - CHECKBOX_ALL_LISTVIEW
    - ICON_ROWACTION
    - LINK_INACTIONS
    - MAINTENANCE_STATE_INLISTVIEW
    - SUSPEND_MAINTENANCE_POPUPCOMMENTS
    - LINK_COMMON
    - REQUEST_ROW
    - NO_MAINTENANCE
    - CREATE_REQUEST_FROM_LISTVIEW
    - AJAX_NOTIFIACTION_TEXT
    - MAINTENANCE_HEADING_LOCATOR
    - MAINTENANCE_REQUEST_ID
    - ABC_LOCATOR
    - NO_OF_MAINTENANCE_WITH_STATE
    - LISTVIEW_BUTTONS
    - QUICK_ACTIONS_BUTTON_LISTS
    DetailView:
    - ICON_SPOTEDIT_IN_DESCRIPTION_LOCATOR
    - ICON_SPOTEDIT_IN_RESOLUTION_LOCATOR
    - GOBACK_BUTTON_LOCATOR
    - RESOULTION_LOCATOR_IN_DETAILVIEW
    - SUBTAB_IN_DETAILVIEW_FUNCTION
    - CONFIRM_BOX_IN_DETAILVIEW
    - CLICK_TEMPLATE
data_constants:
  file: com/zoho/automater/selenium/modules/maintenance/requestmaintenance/common/RequestMaintenanceDataConstants.java
  classes:
    RequestMaintenanceDataConstants:
    - API_DATA
    - REQUEST_MAINTENANCE_WITH_HELPCARD
    - API_DATA_ONCE
    - CREATE_MAINTENANCE_WITH_HELPCARD_TEMPLATE
    - API_DATA_DAILY
    - CREATE_MAINTENNACE_USE_CUSTOM_TEMPLATE
annotation_constants:
  file: null
  groups: []
  data: []
preprocess_groups:
- name: create
  creates_count: 1
  local_storage_keys:
  - criteriaValue
  - CIsname
  - template_Name
data_json_keys: []
