module: maintenance
entity: changemaintenance
actions_util:
  file: null
  methods: []
api_util:
  file: null
  methods: []
locators:
  file: com/zoho/automater/selenium/modules/maintenance/changemaintenance/common/ChangeMaintenanceLocators.java
  interfaces:
    ChangeMaintenanceLocators: []
data_constants:
  file: com/zoho/automater/selenium/modules/maintenance/changemaintenance/common/ChangeMaintenanceDataConstants.java
  classes:
    ChangeMaintenanceDataConstants:
    - GET_CHANGE_TEMPLATE
    - SCHEDULE_MAINTENANCE_WEEKLY
    - API_DATA
    - SCHEDULE_MAINTENANCE_YEARLY
    - SCHEDULE_MAINTENANCE_DAILY
    - SCHEDULE_MAINTENANCE_ONCE
    - API_DATA_ONCE
    - EDIT_CHANGE_MAINTENANCE_ONCE
    - API_DATA_DAILY
    - GET_SUBMISSION_REQUESTED_ID
    - SCHEDULE_MAINTENANCE_MONTHLY
    - CREATE_CHANGE_MAINTENANCE_ONCE
    - CREATE_CHANGE_MAINTENANCE
    - GET_SUBMISSION_STAGE_ID
    - STAGE_NAME_TO_SCRIPT
    - SCRIPT_TO_SUBMISSION
annotation_constants:
  file: null
  groups: []
  data: []
preprocess_groups:
- name: create
  creates_count: 0
  local_storage_keys: []
- name: enabledowntimeintemplate
  creates_count: 0
  local_storage_keys: []
- name: changeStageNameChange
  creates_count: 0
  local_storage_keys: []
data_json_keys: []
