module: problems
entity: problem
actions_util:
  file: com/zoho/automater/selenium/modules/problems/problem/utils/ProblemActionsUtil.java
  methods:
  - name: addContentToEditor
    return_type: void
    params: String content
    purpose: ''
  - name: navigateTo
    return_type: void
    params: String listviewFilter, String tableViewName, Boolean searchProblem, String entityID, String subTab
    purpose: ''
  - name: verifyDialogWindowTitle
    return_type: boolean
    params: String title
    purpose: ''
  - name: attachIncident
    return_type: void
    params: String incidentId
    purpose: ''
  - name: detachIncident
    return_type: void
    params: String incidentId
    purpose: ''
  - name: attachChange
    return_type: void
    params: String changeId
    purpose: ''
  - name: detachChange
    return_type: void
    params: String changeId
    purpose: ''
  - name: clickFromActions
    return_type: void
    params: String action
    purpose: ''
  - name: selectTaskTemplateInPopup
    return_type: void
    params: String templateName, String templateId
    purpose: ''
  - name: verifyInHistory
    return_type: ArrayList<Object>
    params: String operationName, String description, String fieldName, String fromValue, String toValue
    purpose: actions.popUp.columnSearch("Template Name", templateName);
  - name: copyProblem
    return_type: void
    params: String moduleName, String entityId
    purpose: ''
  - name: validateUDFFieldValuesInForm
    return_type: ArrayList<String>
    params: JSONObject inputData, String dateFormat
    purpose: ''
  - name: SearchSolution
    return_type: void
    params: String title, boolean isApproveSolList
    purpose: ''
  - name: SelectSolutionAction
    return_type: void
    params: ArrayList<String> title, String action, boolean isApproveSolList
    purpose: ''
  - name: SolutionAttachActions
    return_type: void
    params: ArrayList<String> id, ArrayList<String> title, String action, boolean isApproveSolList
    purpose: ''
  - name: SolutionDetachActions
    return_type: void
    params: String title
    purpose: ''
  - name: switchGraph
    return_type: void
    params: String widgetTitle, String switchToGraph
    purpose: ''
  - name: maximizeWidget
    return_type: void
    params: String widgetTitle
    purpose: ''
  - name: criteriaBuilderForDate
    return_type: void
    params: String criteriaString, Long dateLongVal
    purpose: ''
  - name: createProblem
    return_type: void
    params: JSONObject inputData
    purpose: a[@class='cal-icon-holder']"), "");
  - name: verifyTooTipTxt
    return_type: void
    params: String containsValue
    purpose: addContentToEditor(description);
  - name: setCustomFilterCriteria
    return_type: void
    params: JSONArray criteriaData, boolean isAdditionalField
    purpose: addContentToEditor(description);
  - name: jsonToMap
    return_type: HashMap<String, Object>
    params: JSONObject jsonObject
    purpose: ''
  - name: jsonArrayToList
    return_type: ArrayList<String>
    params: JSONArray jsonArray
    purpose: ''
  - name: fillDateTimeField
    return_type: void
    params: Long value
    purpose: ''
  - name: fillHTMLFieldCustomActions
    return_type: void
    params: String name, String value
    purpose: ''
  - name: fillCreatedByCriteriaFieldUI
    return_type: void
    params: (none)
    purpose: '*[@class=''ze_area wcag-focus-visible'']"), ""));'
  - name: fillCreatedByCriteriaFieldUI
    return_type: void
    params: Long dateInMillis, String condition
    purpose: onehour before
  - name: createProblemAndFillInputData
    return_type: void
    params: JSONObject inputData
    purpose: ''
  - name: editProblemUI
    return_type: void
    params: String entityId,JSONObject inputData
    purpose: ''
  - name: clearUdfValue
    return_type: void
    params: String fieldName
    purpose: ''
api_util:
  file: com/zoho/automater/selenium/modules/problems/problem/utils/ProblemAPIUtil.java
  methods:
  - name: storeProblemModuleId
    return_type: void
    params: (none)
    purpose: ''
  - name: addNotestoProblem
    return_type: void
    params: String entityId, JSONObject noteInputData
    purpose: ''
  - name: addWorklogtoProblem
    return_type: String
    params: String entityId
    purpose: ''
  - name: addRemindertoProblem
    return_type: String
    params: String entityId
    purpose: ''
  - name: assignSiteGrouptoTechnician
    return_type: HashMap<String, String>
    params: (none)
    purpose: ''
  - name: addSite
    return_type: void
    params: (none)
    purpose: ''
  - name: addAssets
    return_type: void
    params: (none)
    purpose: ''
  - name: addCiItems
    return_type: void
    params: (none)
    purpose: ''
  - name: addAndAssociateIncident
    return_type: String
    params: (none)
    purpose: ''
  - name: associateIncidentAPI
    return_type: String
    params: String problemId
    purpose: ''
  - name: searchChange
    return_type: JSONObject
    params: String name, String description
    purpose: ''
  - name: associateChange
    return_type: String
    params: (none)
    purpose: ''
  - name: associateChangeAPI
    return_type: String
    params: String problemId, TestCaseData changedata
    purpose: ''
  - name: searchProblemUDF
    return_type: JSONObject
    params: String fieldName, String fieldType
    purpose: ''
  - name: addProblemUDF
    return_type: void
    params: String fieldName, String fieldType
    purpose: ''
  - name: deleteProblemUDF
    return_type: void
    params: String fieldName, String fieldType
    purpose: ''
  - name: searchProblemTemplate
    return_type: JSONArray
    params: String name
    purpose: ''
  - name: createProblemTemplate
    return_type: String
    params: String dataId
    purpose: ''
  - name: createProblemTemplate
    return_type: String
    params: JSONObject inputData
    purpose: ''
  - name: addUDFTemplate
    return_type: String
    params: String name
    purpose: ''
  - name: addProblem
    return_type: String
    params: TestCaseData data
    purpose: ''
  - name: addProblemForFilters
    return_type: HashMap<String, String>
    params: String filter
    purpose: ''
  - name: createProblemAddTaskandTemplate
    return_type: HashMap<String, String>
    params: String entityName, String apiPath, JSONObject problemInputData, String requirement
    purpose: ''
  - name: createProblemForTrigger
    return_type: void
    params: String testCase
    purpose: siva
  - name: createProblemTriggerViaAPICreatedDate
    return_type: void
    params: (none)
    purpose: don't delete this line, problemId variable is capitalized,Impacts in other areas.
  - name: createTaskInProblem
    return_type: String
    params: TestCaseData taskdata
    purpose: ''
  - name: createProblemTemplateWithCIInvolved
    return_type: void
    params: (none)
    purpose: ''
  - name: addLCInProblem
    return_type: void
    params: String plcData
    purpose: ''
locators:
  file: com/zoho/automater/selenium/modules/problems/problem/common/ProblemLocators.java
  interfaces:
    ProblemLocators:
    - CLICK_SYSTEM_LOG
    - GET_SYSTEM_LOG_MESSAGE
    - INPUT_FIELDS_BY_ID
    - ERRORLABEL_BYNAME
    - INPUT_FIELDS_BY_NAME
    - BYID_BYVALUE
    - EDIT_BYNAME
    - CONFIRM_BYSPAN
    - YES_BYSPAN
    - CANCEL_BYNAMEINCHILD
    - SAVE_BYNAMEINCHILD
    - SAVE_BYNAMEINPUTINCHILD
    - TASK_IN_FORM
    - TASK_SECTION
    - CRITERIA_PIPED_LOCATORS
    - CLICK_MULTI_LOOKUP_UDF
    - UDF_FIELD_IN_PROBLEM_FORM
    - UDF_FIELD_IN_PROBLEM_FORM
    - UDF_VALUE_IN_PROBLEM_FIELD_IN_FORM
    - UDF_VALUE_IN_PROBLEM_FIELD_IN_DETAIL_PAGE
    - CHECKBOX_DATAROWID
    - ACTIONGEAR_DATAROWID
    - ACTIONGEAR_OPTIONS
    - ICN_NOTES_DATAROWID
    - ROWCONTENT_DATAROWID
    - ROWCONTENT_BYSPAN_DATAROWID
    - TITLE
    - TITLE_INTABLEROW
    - ICN_EDIT
    - TRASH_PROBLEM
    - EMPTY_TEXT
    - NEW_PROBLEM_BTN
    - ICN_LISTVIEW
    - BTN_YES_POPUP
    - BTN_ADD_POPUP
    - BTN_ADDNOTES_POPUP
    - DIV_NOTECONTENT_POPUP
    - CLICK_VERIFY_PROBLEM_WITH_ENTITYID
    - GO_TO_DETAILPAGE_USING_NAME
    - NO_BUTTON_POPUP
    - YES_BUTTON_POPUP
    - CUSTOM_VIEW_SAVE
    - CLICK_SPAN_DATA_REF_NAME
    Detailview:
    - MODULE_TITLE
    - CUSTOM_MENU_ACTION_BTN
    - CUSTOM_MENU_ITEM
    - ICN_SPOTEDIT_SAVE
    - ICN_DESP_EDIT
    - BTN_SAVE
    - BTN_SAVE_POPUP
    - RADIOBTN_YES
    - RADIOBTN_NO
    - RHS_ASSOCIATEDINCIDENT
    - RHS_ASSOCIATEDINCIDENT_COUNT
    - RHS_ASSOCIATEDCHANGE
    - RHS_ASSOCIATEDCHANGE_COUNT
    - ICN_ATTACHMENT
    - TXT_TITLEINROW
    - TITLEINROW
    - SELECT_CHECKBOX_ENTITYID
    - CHECKBOX_DATAROWID
    - DETAILVIEW_ACTIONGEAR_DATAROWID
    - ACTIONGEAR_OPTIONS
    - TITLE_DATAROWID
    - CHECKBOX_PKCOLID
    - UIDIALOG_TITLE
    - ACTIONS_MENU
    - PROBLEM_TITLE
    - COPY_BUTTON
    - DATE_ERR_MSG
    - PROBLEM_ATTACHMENT
    - APPLY_BUTTON
    - PROBLEM_TEMPLATE
    - ICN_ADDDETAILS
    - ICN_EDITDETAILS
    - ICN_ATTACHFILE
    - ICN_SECTIONOPEN
    - DIV_DETAILS
    - REFFERED_SOLUTION
    - REFFERED_SOLUTION_DETAILS
    - TASKSTAB_BTN
    - ADD_TASKS_BTN
    - ENTITYINROW
    - ROW_STATUS
    - ROW_SCHEDULEEND
    - ORGANIZE_ENTITY
    - DEPENDENCY_NODE
    - BTN_CLOSEDEPENDENCY
    - BTN_MOVEUP
    - BTN_MOVEDOWN
    - DROPDWN_ADDTASK
    - LINK
    - LINK
    - ICN_DELETELINK
    - TASK_TEMPLATE
    - NO_TASKS
    - TASK_FIELD
    - BACK_BUTTON
    - ICN_EDITWL
    - ICN_DELETEWL
    - NO_WORKLOGS
    - ICN_ADD_NOTE
    - ICN_EDIT_NOTE
    - ICN_DELETE_NOTE
    - TXT_CONVERSATION_NOTES
    - EMPTY_CONVERSATION
    - TO_DROPDOWN_LOCATOR
    - REPLY_ICON
    - FORWARD_ICON
    - EXPAND_NOTIFICATION
    - TO_NOTIFICATION
    - RESEND_ICON
    - NEW_CHANGE
    - CHANGE_SECTION
    - CHANGE_TABLE
    - POPOUT_CHANGE
    - INCIDENT_SECTION
    - INCIDENT_TABLE
    - BTN_ATTACH_INCIDENT
    - BTN_DETACH_INCIDENT
    - BTN_ATTACH_CHANGE
    - BTN_DETACH_CHANGE
    - BTN_ASSOCIATE_INCIDENTS
    - BTN_ASSOCIATE_POPUP
    - NO_REQUESTS
    - NO_CHANGES
    - HISTORY_SORT
    - HISTORY_FILTER
    - HISTORY_DATEPICKER
    - HISTORY_SELECTEDDATE
    - HISTORY_DATE_OPTION
    - HISTORY_COLUMN
    - HISTORY_OPERATION
    - RECENT_OPERATION
    - LAST_OPERATION
    - HISTORY_OPERATION_DESCRIPTION
    - HISTORY_OPERATION_DESCRIPTIONDIV
    - LAST_OPERATION_DESCRIPTIONDIV
    - RECENT_OPERATION_DESCRIPTION
    - RECENT_OPERATION_DESCRIPTIONDIV
    - RECENT_OPERATION_DESCRIPTIONDIVTEXT
    - RECENT_OPERATION_DESCRIPTIONDIVSPAN
    - RECENT_OPERATION_DESCRIPTIONSPAN
    - RECENT_CLICKHERE
    - DESCRIPTION
    - DESCRIPTION_AFTER
    - DESCRIPTION_BEFORE
    - RECENT_OPERATION_FIELDNAME
    - RECENT_OPERATION_FROMVALUE
    - RECENT_OPERATION_TOVALUE
    - REMINDER_OPTION
    - NO_REMINDERS
    - DRPDWN_FILTER
    - TXT_OPTION
    - DIALOG_MESSAGE
    - TXT_DIALOG_MESSAGE
    - CHKBOX_STATUS
    - SELECT_VALUES_IN_POPUP_FILTER
    - INPUT_SERVICE_AFFECTED
    - SOLUTION_SUBTAB_SECTIONS
    - CLICK_VERIFY_ARCHIEVED_INCIDENTS
    - CLICK_VERIFY_RECENT_INCIDENTS
    - ASSOCIATED_REQUEST_IN_PROBLEM
    - CLICK_NOTES_ICON_ASSOCIATIONS
    - SOLUTIONS_FILTER
    - SEARCH_SOLUTION
    - SELECT_RADIO_WITH_SUBJECT
    - SOLUTION_SEARCH_CANCEL
    - REFERRED_SOLUTION_MORE_LOCATOR
    - REFERED_SOLUTION_DETACH_ICON
    - SOLUTION_TEXT
    - REFERRED_SOLUTION_COUNT_UI
    - REFERED_SOLUTION_HOVER
    - REFERED_SOLUTION_HOVER_ELEMENT1
    - REFERED_SOLUTION_HOVER_ELEMENT2
    - REFERED_SOLUTION_HOVER_ELEMENT3
    - REFERRED_SOLUTION_VIEW_DETAIL_POPUP
    - REFERRED_SOLUTION_TITLE_POPUP
    - REFERRED_SOLUTION_STATUS_POPUP
    - REFERRED_SOLUTION_DESCRIPTION_POPUP
    - REFERRED_SOLUTION_DETAILS_POPUP
    - WATER_MARK_TITLE
    - LASTEST_HISTORY_OPERATION
    - LATEST_HISTORY
    - DELETE_ATTACH
    - ATTACHMENT_FILE_NAME
    - REQUEST_HISTORY_MORE_LOCATOR
    - PLC_TRANSITION_STATUS
    - PLC_TRANSITION_STATUS_DETAILS_VIEW
    - PLC_TRANSITION_NAME
    - PLC_NO_TRANSITION
    - PLC_NO_TRANSITION_DETAIL_VIEW
    - PLC_TRANSITION_NAME_DETAILS_VIEW
    - PROBLEM_CIS_INVOLVED_FIELD
    - SYSTEM_NOTIFICATION_UNCHECK
    - VERIFY_NOTE_DESCRIPTION
    - FORM_FIELDS_LABEL
    - DROPDOWN_OPTION
    - DETAILSPAGE_SPOT_EDIT
    Popup:
    - POPUP_DATE
    - VERIFY_NO_NOTES_PRESENT
    - CLOSE_ICON_IN_POPUP
    - ADD_NOTE_IN_POPUP
    - ICN_HELP_CPYPB
    - INPUT_TEMPLATE_CPYPB
    - COPYPB_TITLE
    - COPYFIELDS_GENERAL_INPUT
    - COPYFIELDS_ANALYSIS_INPUT
    - COPYFIELDS_SOLUTION_INPUT
    - COPYFIELDS_GENERAL_CHKBOX
    - COPYFIELDS_ANALYSIS_CHKBOX
    - COPYFIELDS_SOLUTION_CHKBOX
    - SWITCH_POPUP_IFRAME_IN_RECENT_POPUP
    HistoryLocators:
    - DESCRIPTION
data_constants:
  file: com/zoho/automater/selenium/modules/problems/problem/common/ProblemDataConstants.java
  classes:
    ProblemDataConstants:
    - CREATE_CUSTOMER
    - EDIT_PROBLEM_LC_WITH_UDF
    - MYOPEN
    - CREATE_PROBLEM_VIA_API_TRIGGER
    - COPYPROBLEM
    - WORKAROUNDEDIT
    - UPDATE_IMPACT
    - SEND_NOTIFICATION_CONVERSATION
    - UPDATE_TITLE
    - ADDTEMPLATE
    - PROBLEM_WORKFLOW_ORGROLES
    - MYRESOLVED
    - CRITERIA_CONDITION_UDFDATE
    - PROBLEM_CREATE_API
    - WORKAROUND
    - SPOTEDIT_SGT
    - UPDATE_UDF
    - CUSTOM_DATA_FOR_PROBLEM_FAFR
    - CMDB_TEAM
    - ADDUDFTEMPLATE
    - DEFAULTCOLUMNS
    - MYONHOLD
    - ADD_UDFWITHVALUES
    - API_PROBLEMDATA2
    - CRITERIA_CONDITION_CREATEDDATE
    - API_PROBLEMDATA1
    - EDIT_PROBLEM_UI
    - PROBLEM_DATA_FOR_TRIGGER
    - CANCELED
    - IMPACT_DETAILS
    - SEARCH_PROBTEMPLATE
    - API_PROBLEMDATA_CUSTOMTEMPLATE
    - CREATE_PROBLEM_VIA_API_WITH_DESCRIPTION
    - SPOTEDIT_CATEGORY
    - ADD_PROBLEM_IN_CUSTOM_TEMPLATE_WITH_UDF_UI
    - SEARCHCHANGE_NAME
    - ADDNOTES_WITH_USER
    - UPDATE_GROUP
    - TRANSITION_MANDATORY_FIELDS
    - CREATE_REQUEST
    - SPOTEDIT_INVALID_DATES
    - SEARCH_VH
    - TASKDEPENDENCIES
    - PROBLEM_CRITERIA_CONDITION_ACROSS_MODULES
    - MYCLOSED
    - PLCFORPROBLEM
    - COPYPROBLEM_FAFR
    - PROBLEM_API_GROUP_DEFAULT_TEMP
    - CREATE_PROBLEM_FOR_WORKFLOW_WITH_UDF_API
    - SPOTEDIT_INVALID_DATES_ADDPAGE
    - CREATE_PROBLEM_FOR_WORKFLOW
    - PROBLEM_DATA_WITH_CUSTOM_TEMPLATE
    - SEARCH_CMDB_PEOPLE
    - MYCANCELED
    - CHOOSEDEFAULTCOLUMNS
    - API_PROBLEMWITHUDFTEMPLATE
    - UPDATE_REPORTED_BY
    - ADD_PROBLEM_UI
    - VIRTUALHOST
    - UPDATE_URGENCY
    - PROBLEM_API_SITE_WITH_REGION_DEFAULT_TEMP
    - API_ADDNOTES
    - ASSOCIATEINCIDENT_API
    - SYMPTOMSEDIT
    - UI_PROBLEMDATA1
    - CREATE_PROBLEM_VIA_API
    - PROBLEM_WORKFLOW_APPROVAL
    - API_UPDATE_NOTES
    - ADD_UDF
    - UPDATE_DESCRIPTION
    - UPDATE_PRIORITY
    - RESOLVED
    - PROBLEM_API_BASE_SITE_DEFAULT_TEMP
    - UPDATE_TECHNICIAN
    - ADD_NOTES_FROM_LISTVIEW
    - ONHOLD
    - UPDATE_ASSETS
    - CREATE_WORKAROUND
    - PROBLEM_CUSTOM_TEMPLATE_WORKFLOW
    - WORKAROUND_ATTACH
    - API_PROBLEM_WITH_CUSTOM_TEMPLATE
    - CREATE_PROBLEM_IN_CUSTOM_TEMPLATE_WITH_UDF_API
    - PROBLEM_DATA_FOR_FAFR_FIELD_CHANGE
    - CMDB_PEOPLE
    - GETPROBLEMMODULEINFO
    - PROBLEM_API_CUSTOM_SITE_DEFAULT_TEMP
    - ADD_PROBLEM_VIA_API
    - SOLUTIONFORPROBLEM
    - API_PROBLEMDATA_APPROVAL
    - SYMPTOMS
    - CREATE_TECHNICIANGROUP
    - RESOLUTION
    - API_PROBLEMDATA_CUSTMENU
    - SEARCH_PROBLEMSSITE
    - ASSOCIATECHANGE_API
    - PROBLEM_WORKFLOW_REQUEST_ASSOCIATION
    - TABLE_SETTINGS
    - CREATE_PROBLEM_VIA_API_WITH_DUE_BY_DATE
    - ROOT_CAUSEEDIT
    - CRITERIA_CONDITION_IS_CREATED_DATE
    - SEARCH_CMDB_TEAM
    - PROBLEM_DATA_WORKFLOW_TECHGROUPS
    - IMPACT_DETAILSEDIT
    - SEARCH_UDF
    - RESOLUTION_TEMPLATE_WORKAROUND
    - SPOTEDIT_VALID_DATES
    - PROBLEM_WORKFLOW_REGIONAL_ROLES
    - PLCFORPROBLEMWITHUDF
    - SPOTEDIT
    - CREATE_PROBLEM_FOR_CUSTOM_MENU
    - PROBLEM_WORKFLOW_CLOSURE_RULES
    - PROBLEM_API_GROUP_CUSTOM_TEMP_WORKFLOW
    - CREATECUSTOMER
    - SINGLE_NODE_NOTIFICATION
    - SEARCH_WORKSTATION
    - ADD_PROBLEM_VIA_API_FOR_UNIQUE_STRING
    - ROOT_CAUSE
    - API_PROBLEMDATA_WITHCUSTOMER
    - WORKSTATION
    - CREATE_PROBLEM_WITH_SITE_VIA_API
    - RESOLUTIONEDIT
    - API_PROBLEMDATA_COUNT_10
    - COLUMN_CHOOSER_LISTVIEW
    - PROBLEM_WORKFLOW_ASSOCIATEROLES
    - CLOSED
    - UPDATE_STATUS
    - REMOVE_REPORTEDBY
    - CREATE_PROBLEM_TRIGGER_CREATED_DATE_VIA_API
    - CREATE_PROBLEM_WORKFLOW_NOTIFICATIONS
    - CREATE_PROBLEM_VIA_API_WITH_URGENCY
annotation_constants:
  file: null
  groups: []
  data: []
preprocess_groups: []
data_json_keys:
- API_ProblemData1
- API_ProblemData2
- API_ProblemData_Approval
- API_ProblemData_CustMenu
- API_ProblemData_count_10
- API_ProblemData_customTemplate
- API_ProblemData_withCustomer
- API_ProblemWithUDFTemplate
- API_Problem_with_Custom_Template
- AddNotes_With_User
- Api_AddNotes
- Api_Update_notes
- AssociateChange_API
- AssociateIncident_API
- Canceled
- Closed
- Column_Chooser_Listview
- CopyProblem_Fafr
- DefaultColumns
- Impact_Details
- Impact_DetailsEdit
- MyCanceled
- MyClosed
- MyOpen
- MyResolved
- MyonHold
- Remove_ReportedBy
- Resolution
- ResolutionEdit
- Resolved
- Root_Cause
- Root_CauseEdit
- Search_CMDB_People
- Search_CMDB_Team
- Search_UDF
- Search_workstation
- Symptoms
- SymptomsEdit
- TaskDependencies
- UI_ProblemData1
- Update_Group
- Update_Impact
- Update_Priority
- Update_Status
- Update_Title
- Update_description
- Update_reported_by
- Update_technician
- Update_urgency
- VirtualHost
- Workaround
- WorkaroundEdit
- Workaround_attach
- Workstation
- addTemplate
- addUDFTemplate
- add_Notes_From_ListView
- add_problem_UI
- add_problem_in_custom_template_with_udf_ui
- add_problem_via_api
- add_problem_via_api_for_unique_string
- add_udf
- add_udfwithvalues
- chooseDefaultColumns
- cmdb_people
- cmdb_team
- copyProblem
- createCustomer
- create_customer
- create_problem_for_custom_menu
- create_problem_for_workflow
- create_problem_for_workflow_with_udf_api
- create_problem_in_custom_template_with_udf_api
- create_problem_trigger_created_date_via_api
- create_problem_via_api
- create_problem_via_api_trigger
- create_problem_via_api_with_description
- create_problem_via_api_with_due_by_date
- create_problem_via_api_with_urgency
- create_problem_with_site_via_api
- create_problem_workflow_notifications
- create_request
- create_technicianGroup
- create_workaround
- criteria_condition_createddate
- criteria_condition_is_created_date
- criteria_condition_udfdate
- custom_data_for_problem_fafr
- edit_problem_lc_with_udf
- edit_problem_ui
- getProblemModuleInfo
- onHold
- plcForProblem
- plcForProblemWithUdf
- problem_API_Base_Site_Default_Temp
- problem_API_Custom_Site_Default_Temp
- problem_API_Site_with_Region_Default_Temp
- problem_Api_Group_Custom_Temp_workflow
- problem_Api_Group_Default_Temp
- problem_Create_API
- problem_Custom_Template_workflow
- problem_Data_workflow_Techgroups
- problem_criteria_condition_across_modules
- problem_data_for_fafr_field_change
- problem_data_for_trigger
- problem_data_with_custom_template
- problem_workflow_Associateroles
- problem_workflow_Closure_rules
- problem_workflow_Orgroles
- problem_workflow_approval
- problem_workflow_regional_roles
- problem_workflow_request_association
- resolution_template_workaround
- searchChange_Name
- search_ProbTemplate
- search_ProblemsSite
- search_VH
- send_notification_conversation
- single_node_notification
- solutionForProblem
- spotEdit
- spotEdit_category
- spotEdit_sgt
- spotedit_invalid_dates
- spotedit_invalid_dates_addpage
- spotedit_valid_dates
- table_Settings
- transition_mandatory_fields
- update_assets
- update_udf
