module: problems
entity: reminder
actions_util:
  file: null
  methods: []
api_util:
  file: null
  methods: []
locators:
  file: com/zoho/automater/selenium/modules/problems/reminder/common/ReminderLocators.java
  interfaces:
    ReminderLocators: []
data_constants:
  file: com/zoho/automater/selenium/modules/problems/reminder/common/ReminderDataConstants.java
  classes:
    ReminderDataConstants:
    - ADDREMINDER
    - API_ADDREMINDER1
annotation_constants:
  file: null
  groups: []
  data: []
preprocess_groups: []
data_json_keys:
- API_AddReminder1
- AddReminder
