module: problems
entity: note
actions_util:
  file: null
  methods: []
api_util:
  file: null
  methods: []
locators:
  file: com/zoho/automater/selenium/modules/problems/note/common/NoteLocators.java
  interfaces:
    NoteLocators: []
data_constants:
  file: com/zoho/automater/selenium/modules/problems/note/common/NoteDataConstants.java
  classes:
    NoteDataConstants:
    - ADD_NOTES_FROM_LISTVIEW
annotation_constants:
  file: null
  groups: []
  data: []
preprocess_groups: []
data_json_keys:
- add_Notes_From_ListView
