module: problems
entity: task
actions_util:
  file: null
  methods: []
api_util:
  file: null
  methods: []
locators:
  file: com/zoho/automater/selenium/modules/problems/task/common/TaskLocators.java
  interfaces:
    TaskLocators: []
data_constants:
  file: com/zoho/automater/selenium/modules/problems/task/common/TaskDataConstants.java
  classes:
    TaskDataConstants:
    - API_PROBLEMTASKWITHGROUPANDOWNER
    - API_PROBLEMTASK1
    - API_PROBLEMTASK2
    - UI_PROBLEMTASK1
annotation_constants:
  file: null
  groups: []
  data: []
preprocess_groups: []
data_json_keys:
- API_ProblemTask1
- API_ProblemTask2
- API_ProblemTaskWithGroupAndOwner
- UI_ProblemTask1
