module: problems
entity: worklog
actions_util:
  file: null
  methods: []
api_util:
  file: null
  methods: []
locators:
  file: com/zoho/automater/selenium/modules/problems/worklog/common/WorklogLocators.java
  interfaces:
    WorklogLocators: []
data_constants:
  file: com/zoho/automater/selenium/modules/problems/worklog/common/WorklogDataConstants.java
  classes:
    WorklogDataConstants:
    - API_WORKLOG1
    - UI_WORKLOG1_EDITDATA
    - API_WORKLOG2
    - UI_WORKLOG1
annotation_constants:
  file: null
  groups: []
  data: []
preprocess_groups: []
data_json_keys:
- API_Worklog1
- API_Worklog2
- UI_Worklog1
- UI_Worklog1_EditData
