module: projects
entity: milestone
actions_util:
  file: null
  methods: []
api_util:
  file: null
  methods: []
locators:
  file: com/zoho/automater/selenium/modules/projects/milestone/common/MilestoneLocators.java
  interfaces:
    MilestoneLocators: []
    MilestoneListview:
    - CLICK_ROW_ACTIONS_WITH_ENTITYID
    - CLICK_EDIT_IN_ACTIONS_ICON
    - CLICK_DELETE_IN_ACTIONS_ICON
    - SELECT_CHECKBOX_WITH_ENTITYID
    - VERIFY_MILESTONE_WITH_ENTITYID
    - CLICK_MILESTONE_WITH_ENTITYID
    - SELECT_GLOBAL_CHECKBOX_MILESTONE
    - VERFIFY_MILESTONE_STATUS_WITH_ENTITYID
    - CLICK_CLOSE_BUTTON_IN_MILESTONE_TAB
    - VERIFY_MILESTONE_OWNER_WITH_ENTITYID
    - GET_MILESTONE_ORDER_WITH_ENTITY_ID
    - CLICK_QUICK_ADD
    - TYPE_MILESTONE_TITLE_INPUT
    - VERIFY_MILESTONE_USING_TITLE
    - VERIFY_DIALOG_BOX_TITLE_NAME
    - VERIFY_CONTENT_IN_DIALOG_BOX
    Popup:
    - SELECT_MILESTONE_IN_POPUP_WITH_ENTITYID
    - MOVE_UP_IN_ORGANIZE_MILESTONE_POPUP
    - MOVE_DOWN_IN_ORGANIZE_MILESTONE_POPUP
    - MOVE_BY_IN_ORGANIZE_MILESTONE_POPUP
    - CLICK_APPLY_BTN_IN_ORGANIZE_MILESTONE_POPUP
    - CLICK_CANCEL_BTN_IN_ORGANIZE_MILESTONE_POPUP
    - CLICK_DELETE_BUTTON_IN_POPUP
data_constants:
  file: com/zoho/automater/selenium/modules/projects/milestone/common/MilestoneDataConstants.java
  classes:
    MilestoneDataConstants:
    - ADD_MILESTONE
    - ADD_MILESTONE_MILESTONE_COUNT_2
    - EDIT_MILESTONE
    - ADD_MEMBERS
annotation_constants:
  file: com/zoho/automater/selenium/modules/projects/milestone/common/MilestoneAnnotationConstants.java
  groups:
  - constant: CREATE_PROJECT
    value: createproject
  - constant: CREATE_PROJECT_AND_MILESTONE
    value: createprojectandmilestone
  - constant: CREATE_PROJECT_WITH_MULTIPLE_MILESTONE
    value: createprojectwithmultiplemilestone
  - constant: CREATE_PROJECT_WITH_MEMBERS
    value: createprojectwithmembers
  - constant: CREATE_PROJECT_WITH_MEMBERS_AND_MILESTONE
    value: createprojectwithmembersandmilestone
  - constant: CREATE_PROJECT_WITH_MULTIPLE_MILESTONE_AND_MEMBERS
    value: createprojectwithmultiplemilestoneandmembers
  data:
  - constant: ADD_MILESTONE
    value: add_milestone
  - constant: ADD_MILESTONE_MILESTONE_COUNT_2
    value: add_milestone_milestone_count_2
  - constant: ADD_MEMBERS
    value: add_members
preprocess_groups: []
data_json_keys:
- add_members
- add_milestone
- add_milestone_milestone_count_2
- edit_milestone
