module: projects
entity: project
actions_util:
  file: com/zoho/automater/selenium/modules/projects/project/utils/ProjectActionsUtil.java
  methods:
  - name: getCount
    return_type: Integer
    params: Locator locator
    purpose: ''
  - name: clickSpotEditField
    return_type: void
    params: String field, String input
    purpose: ''
  - name: uploadFileInRHS
    return_type: void
    params: String fileName
    purpose: ''
  - name: uploadFileInDetails
    return_type: void
    params: String fileName
    purpose: ''
  - name: verifyDetailsAttachment
    return_type: Boolean
    params: int count, ArrayList<String> filenames
    purpose: ''
  - name: verifyRHSAttachment
    return_type: Boolean
    params: int count, ArrayList<String> filenames
    purpose: ''
  - name: pressEscapeKey
    return_type: void
    params: (none)
    purpose: ''
  - name: uploadFile
    return_type: void
    params: Locator locator, String fileName
    purpose: ''
  - name: uploadFile
    return_type: void
    params: String fileName, String mode
    purpose: '}else {'
  - name: verifyAjaxMessage
    return_type: Boolean
    params: String text
    purpose: ''
  - name: globalCheckboxSelect
    return_type: void
    params: String entityId
    purpose: ''
  - name: globalCheckboxSelectInTemplateForTasks
    return_type: void
    params: String entityId
    purpose: ''
  - name: columnSearchForInitiatedChangesListView
    return_type: void
    params: String column, String value
    purpose: ''
  - name: setTableViewType
    return_type: void
    params: String viewType
    purpose: change to template view in details tab section
  - name: editTaskUsingRowActionsViaMilestone
    return_type: void
    params: (none)
    purpose: ''
  - name: deleteTaskUsingRowActionsViaMilestone
    return_type: void
    params: (none)
    purpose: ''
  - name: deleteMultipleTaskUsingRowActionsViaMilestone
    return_type: void
    params: (none)
    purpose: ''
  - name: clickAddTaskInAddTaskDropdownViaMilestone
    return_type: void
    params: (none)
    purpose: ''
  - name: closeSingleTaskViaMilestone
    return_type: void
    params: (none)
    purpose: ''
  - name: closeMultipleTaskViaMilestone
    return_type: void
    params: (none)
    purpose: ''
  - name: triggerSingleTaskViaMilestone
    return_type: void
    params: (none)
    purpose: ''
  - name: selectUsersInNotesEditor
    return_type: void
    params: String message
    purpose: ''
  - name: selectTaskOwnersInNotesEditor
    return_type: void
    params: String message
    purpose: ''
  - name: navigateTo
    return_type: void
    params: String listviewFilter, String tableViewName, String searchProject, String entityID, String subTab
    purpose: ''
api_util:
  file: com/zoho/automater/selenium/modules/projects/project/utils/ProjectAPIUtil.java
  methods:
  - name: createProject
    return_type: void
    params: String testCase
    purpose: ''
  - name: createMilestone
    return_type: void
    params: String milestoneDataID
    purpose: milestone in project
  - name: createProjectWithMilestone
    return_type: void
    params: String projectDataID, String milestoneDataID
    purpose: ''
  - name: createProjectWithMultipleMilestones
    return_type: void
    params: String projectDataID, String milestoneDataID
    purpose: LocalStorage.store("milestoneId", milestone.optString("id"));
  - name: createProjectWithMultipleMilestone
    return_type: void
    params: String projectDataID, String milestoneDataID, LinkedHashMap<String, FieldDetails> fields
    purpose: ''
  - name: createComments
    return_type: void
    params: String commentDataID
    purpose: project comments
  - name: createProjectWithComments
    return_type: void
    params: String projectDataID, String commentDataID
    purpose: ''
  - name: createMembers
    return_type: void
    params: String memberDataID
    purpose: ''
  - name: createProjectWithMembers
    return_type: void
    params: String testCase, String memberDataID
    purpose: ''
  - name: createProjectWithMembersAndMilestone
    return_type: void
    params: String testCase, String memberDataID, String milestoneDataID
    purpose: ''
  - name: createProjectWithMultipleMilestoneAndMembers
    return_type: void
    params: String projectDataID, String milestoneDataID, LinkedHashMap<String, FieldDetails> fields, String memberDataID
    purpose: LocalStorage.store("milestoneId", milestone.optString("id"));
  - name: createProjectWithCommentsAndMembers
    return_type: void
    params: String projectDataID, String commentDataID, String memberDataID
    purpose: LocalStorage.store("memberId", member.optString("id"));
  - name: projectCreation
    return_type: Map<String, JSONObject>
    params: String testCase
    purpose: LocalStorage.store("memberId", member.optString("id"));
  - name: editProject
    return_type: Map<String, JSONObject>
    params: TestCaseData testCase
    purpose: ''
  - name: ProjectWithMilestone
    return_type: Map<String, JSONObject>
    params: String projectDataID, String milestoneDataID
    purpose: ''
locators:
  file: com/zoho/automater/selenium/modules/projects/project/common/ProjectLocators.java
  interfaces:
    ProjectLocators:
    - CLICK_LISTVIEW_FILTERS
    - SELECT_PROJECTS_FILTER
    - TRASHED_PROJECTS_FILTER
    - VERFIY_PROJECT_WITH_ENTITYID
    - CLICK_ROW_ACTIONS_WITH_ENTITYID
    - ACTIONS_LIST
    - VERIFY_PROJECT_NAME_IN_LISTVIEW
    - VERIFY_EDIT_PROJECT_TEMPLATE_PAGE_OPENED
    - SELECK_CHECKBOX_WITH_ENTITYID
    - SELECT_CHECKBOX_ENTITYID_PROJECT
    - VERIFY_WITH_ENTITYID
    - VERIFY_RELEASE_TITLE_IN_PROJECT_ASSOCIATION
    - VERIFY_PROJECT_STATUS_IN_LISTVIEW
    - NO_PROJECTS_WITH_STATUS
    - BULK_SELECT_CHECKBOX
    - PAGE_COUNT
    - ROW_USING_ENTITYID
    - NEW_PROJECT_BTN
    - DELETE_BTN
    - IMPORT_PROJECTS_BTN
    - LIST_VIEW_ICON
    - TEMPLATE_VIEW_ICON
    - CUSTOM_FILTER_ICON
    - PROJECT_REQUESTER_ICON_IN_FORM
    - SELECT_RADIO_BTN_IN_POPUP
    - CLICK_SAVE_BUTTON_USING_SUBMIT
    - VERIFY_USER
    - ASSOCIATE_OPTION
    - TITLE_FILED
    - VERIFY_PROJECT_LISTVIEW_SELECTED
    Popup:
    - POPUP_TITLE_TEXT
    - TYPE_PROJECT_TITLE_IN_POPUP
    - CLICK_SAVE_BTN_IN_POPUP
    - TYPE_TEMPLATE_NAME_IN_POPUP
    - CHK_COLUMN_PRESENT
    ProjectDetailview:
    - GO_BACK
    - CLICK_COMMENT
    - VERFIY_ADDED_TEXT_IN_COMMENTS_SUBTAB
    - VERFIY_ADDED_TEXT_IN_REPLY_COMMENTS
    - VERFIY_ADDED_TEXT_IN_REPLY_COMMENTS_USING_NAME
    - COMMENT_HOVER
    - REPLY_COMMENT_HOVER
    - CLICK_EDIT_DELETE_COMMENT
    - CLICK_EDIT_DELETE_REPLY_COMMENT
    - COMMENT_ROW
    - REPLY_COMMENT_ROW
    - CLICK_EDIT_BTN
    - CLICK_CLOSE_BTN
    - MODULE_STATUS
    - VERIFY_CHANGE_ATTACHED_WITH_DATA_ROW_ID
    - CLICK_TIMESHEET_MEMBERS
    - VERIFY_TASK_NAME_IN_TIMESHEET
    - CLICK_SPOT_EDIT_DATE_INPUT
    - DETAILVIEW_ACTIONS_DROPDOWN
    - CLICK_ATTACH_BUTTON
    - FILE_INPUT
    - ATTACHMENT_COUNT
    - ATTACHMENT_IN_DETAILVIEW
    - ATTACHMENT_IN_RHS
    - SPOTEDIT
    - GENERAL_HISTORY_TEXT
    - INPUT_PROJECT_CODE
    - SAVE_TICK_ICON
    - DETAILVIEW_ATTACH_BTN
    - DETAILVIEW_FILE_INPUT
    - INPUT_ESTIMATED_HOURS
    - INPUT_ACTUAL_HOURS
    - INPUT_ESTIMATED_COST
    - INPUT_ACTUAL_COST
    - INPUT_PERCENTAGE_COMPLETED
    - COPY_PROJECT_ACTIONS_DROPDOWN
    - TYPE_PERCENTAGE_COMPLETED
    - VERIFY_COMMENTS_IN_THREAD_VIEW
    - CLICK_LINEAR_VIEW_IN_COMMENTS
    - SELECT_USERS_IN_COMMENT_DROPDOWN
    - GLOBAL_ACTION_ELEMENT
    - GLOBAL_ACTION_ELEMENT_DROPDOWN_BTNS
    - CLICK_SEARCH_ICON_IN_ASSOCIATIONS_SUBTAB
    - VERIFY_CHANGE_ATTACHED_WITH_DISPLAY_ID
    - CHANGES_CASUED_BY_PROJECT_TABLE_HEADER
    - ENABLE_CHECKBOX_CHANGE_ATTACHED_WITH_DISPLAY_ID
    - SELECT_GLOBAL_CHECKBOX_IN_ASSOCIATION_SUBTAB
    - NO_CHANGES_FOUND_IN_THIS_VIEW_IN_ASSOCIATION_SUBATB
    - VERIFY_ASSOCIATIONS_COUNT_IN_RHS
    - CHANGES_CASUED_BY_PROJECT_TABLE
    - CUSTOMER_FIELD_IN_COLUMNCHOOSER
    - MENTIONS_DROPDOWN_IN_COMMENTS
    - TABLE_VIEW_TYPE
    - PROJECT_TITLE
    - LAST_MILESTONE
    ProjectTemplateListview:
    - VERIFY_COPY_PROJECT_TEMPLATE
    TrashedProject:
    - CLICK_BACK_BTN_IN_TRASH_PROJECT
    - CLICK_PROJECT_WITH_ENTITYID_IN_TRASH
    - VERIFY_TRASH_PROJECT_EXPANDED_WITH_ENTITYID
    ImportWizard:
    - ADMIN_VERIFY_IMPORT_PROJECTS_PAGE_OPENED
    - ADMIN_VERIFY_IMPORT_WIZARD_TEXT
    ProjectDetailViewRHS:
    - RHS_ASSOCIATIONS
    - VERIFY_ASSOCIATIONS_TAB_OPENED_REQUEST
    - VERIFY_ASSOCIATIONS_TAB_OPENED_CHANGES_CAUSED_BY_PROJECT
    - VERIFY_ASSOCIATIONS_TAB_OPENED_CHANGES_INITIATED_THE_PROJECT
    - VERIFY_ASSOCIATIONS_TAB_OPENED_RELEASE
    - ATTACH_DETACH_REQUEST
    - ATTACH_DETACH_CHANGES_CAUSED_BY_PROJECT
    - ATTACH_DETACH_RELEASE
    - VERIFY_RHS_STATUS
    - VERIFY_RHS_PRIORITY
    - VERIFY_RHS_OWNER
    - CLICK_RHS_MILESTONES
    - VERIFY_MILESTONE_SUBTAB_OPENED
    - CLICK_RHS_TASKS
    - VERIFY_TASKS_SUBTAB_OPENED
    - ATTACH_DETACH_CHANGES_INITIATED_THE_PROJECT
    - RELEASES_INTIATED_PROJECT
    - RELEASES_INTIATED_BY_MILESTONE
    - RELEASES_INTIATED_BY_MILESTONE_ASSOCIATIONS_PAGE
    RHSPopup:
    - VERIFY_ASSOCIATE_REQUEST_TO_PROJECT_TEXT_IN_POPUP
    - BTN_ASSOCIATE
    - CLICK_LISTVIEW_FILTERS
    - CLICK_CHANGE_LISTVIEW_FILTERS
    - CLICK_ALL_REQUESTS_FILTERS
    - VERIFY_SEARCH_CHANGES_TEXT_IN_POPUP
    - CLICK_ALL_CHANGES_FILTERS
    - VERIFY_ASSOCIATE_RELEASE_TEXT_IN_POPUP
    - CLICK_PROJECTS_LISTVIEW_FILTERS
    - TEXT_IN_POPUP
    - SELECT_RADIOBTN_WITH_ENTITYID
    - SELECK_CHECKBOX_WITH_ENTITYID
    - SELECT_RADIOBTN_WITH_DATA_ROW_ID
    - CHANGE_LISTVIEW_FILTERS_DROPDOWN_IN_POPUP
    - SELECT_GLOBAL_CHECKBOX_IN_POPUP
    ValidationMessage:
    - VERIFY_VALIDATION_MESSAGE
    HistoryLocators:
    - DESCRIPTION
    - ICONS_IN_HISTORY
    - VERIFY_CAN_SELECT_ONLY_15_ITEMS
    - VERIFY_15_ITEMS
    - HISTORY_TEXT
    Association:
    - SELECT_RELEASE_MILESTONE_ASSOCIATION
    - DETACH_RELEASE_MILESTONE
    - ASSOCIATE_RELEASE_MILESTONE
    - RELEASE_ASSOCIATED_HISTORY
    - SELECT_RELEASE_ALERT
    - DISSOCIATE_MILESTONE_ALERT
    - GO_BACK_BUTTON
    - NEW_RELEASE_BUTTON
    - NEW_CHANGE_BUTTON
    - RELEASE_PROJECT_BUTTON
    - SAVE_NEWCHANGE
    - CANCEL_NEWCHANGE
    - NEW_CHANGE_PAGE_POPUP
    - VERIFY_ASSOCIATED_CHANGE
    - VERIFY_ASSOCIATED_CHANGE_CAUSED
    - SEARCH_CHANGE_IN_ASSOCIATION
    - OPEN_CHANGES_DROPDOWN
    - SELECT_DROPDOWN_OPTION_BY_TEXT
    - POPOUT_ICON_BY_CHANGE_ID
    - VERIFY_CHANGE_TITLE_POPOUT
    - VERIFY_HISTORY_STATUS_TEXT
    - CHANGE_SEARCH
    - CHANGE_INITIATED_ACTION_BUTTON
    - OPEN_CHANGES_OPTION_DROPDOWN
    - NO_CHANGE_SELECT_ALERT
    - CLICK_RADIO_SPAN_WITH_CHANGENAME
    - VERIFY_CHANGENAME_ASSOCIATION_SEARCH
    - POPOUT_CHANGEDETAILS_ASSOCIATIONPAGE
    - VERIFY_TITLE_VALUE_NEWCHANGE
    - VERIFY_FIELDVALUES_NEWCHANGE
    - VERIFY_PROJECTDESCRIPTION_NEWCHANGE
    - CLICK_CHECKBOX_BY_TITLE
    - CLICK_CHECKBOX_BY_CHANGE_NAME
    - VERIFY_CHANGE_ASSOCIATION
    - RELEASE_COUNT_INITIATEDBY_MILESTONE
    - NEW_RELEASE_ATTACHMENT_STATUS
    - SEARCH_CHANGE_CAUSED_BYPROJECT
    - TITLE_SEARCH
    - CLICK_GO
    GanttChart:
    - EXPORT_GANTT_CHART
    - GANTT_CHART_PDF
data_constants:
  file: com/zoho/automater/selenium/modules/projects/project/common/ProjectDataConstants.java
  classes:
    ProjectDataConstants:
    - SPOT_EDIT_OWNER
    - HISTORY_PRIORITY_TO_LOW
    - DETAILS_SPOT_EDIT_TEXTAREA_FIELDS_INPUT
    - CHANGE_CASUED_BY_PROJECT_VIA_NEW_CHANGE
    - HISTORY_OWNER
    - CREATE_PROJECT_STATUS_TO_OPEN
    - HISTORY_STATUS_CANCELED
    - SPOT_EDIT_STATUS_TO_ONHOLD
    - CREATE_PROJECT_STATUS_TO_CANCELED
    - SPOT_EDIT_PROJECT_TYPE_TO_RESEARCH
    - CREATE_PROJECTS_FOR_CHANGE_NR
    - TABLE_SETTINGS
    - HISTORY_ACTUAL_COST
    - HISTORY_PROJECT_TYPE_TO_RESEARCH
    - SPOT_EDIT_PROJECT_TYPE_TO_MAINTENANCE
    - HISTORY_PROJECT_TYPE_TO_BUSINESS
    - SPOT_EDIT_PROJECT_REQUESTER
    - LISTVIEW_SEARCH_BY_COLUMN_INPUT
    - SPOT_EDIT_PROJECT_TYPE_TO_INFRASTRUCTURE
    - HISTORY_PROJECT_CODE
    - SPOT_EDIT_PERCENTAGE_COMPLETED
    - CREATE_PROJECT_USING_DEFAULT_PROJECT_TEMPLATE
    - SPOT_EDIT_PROJECT_TYPE_TO_BUSINESS
    - SPOT_EDIT_STATUS_TO_CANCELED
    - RHS_OWNER
    - RHS_PRIORITY_TO_HIGH
    - CREATE_RELEASE_FOR_PROJECT
    - HISTORY_PRIORITY_TO_NORMAL
    - RHS_STATUS_TO_CLOSED
    - HISTORY_PRIORITY
    - ADD_TASK_FROM_TEMPLATE
    - HISTORY_PROJECT_TYPE_TO_MAINTENANCE
    - COPY_PROJECT
    - HISTORY_STATUS_ONHOLD
    - PROJECT_DATA_ASSOCIATION
    - SPOT_EDIT_ESTIMATED_HOURS
    - SPOT_EDIT_ACTUAL_COST
    - HISTORY_ACTUAL_HOURS
    - ADD_COMMENT_UI
    - CREATE_PROJECT_MANDATORY_FIELDS
    - EDIT_PROJECT
    - ADD_MEMBERS
    - ADD_TASK_VIA_ACTIONS
    - PROJECT_CHANGE_ASSOCIATION_DATA
    - RHS_PRIORITY_TO_NORMAL
    - COPY_PROJECT_TEMPLATE
    - HISTORY_PERCENTAGE_COMPLETED
    - CREATE_PROJECT_STATUS_TO_ONHOLD
    - RHS_PRIORITY_TO_MEDIUM
    - HISTORY_PRIORITY_TO_MEDIUM
    - LIST_INFO_CRITERIA_TITLE_SEARCH
    - ADD_COMMENT_API
    - CREATE_PROJECT_STATUS_TO_CLOSED
    - SPOT_EDIT_ACTUAL_HOURS
    - HISTORY_ESTIMATED_HOURS
    - HISTORY_PRIORITY_TO_HIGH
    - RHS_PRIORITY_TO_LOW
    - SPOT_EDIT_ESTIMATED_COST
    - BULK_CREATE_PROJECT_MANDATORY_FIELDS
    - EDIT_COMMENT
    - SPOT_EDIT_STATUS_TO_CLOSED
    - PROJECT_DATA_FOR_TRIGGER
    - HISTORY_STATUS_CLOSED
    - RHS_STATUS_TO_CANCELED
    - DETAILS_SPOT_EDIT_USING_SEARCH_INPUT
    - RHS_STATUS_TO_ONHOLD
    - HISTORY_PROJECT_REQUESTER
    - HISTORY_ESTIMATED_COST
    - SPOT_EDIT_STATUS_TO_OPEN
    - HISTORY_STATUS_TO_OPEN
    - SPOT_EDIT_PROJECT_CODE
    - DETAILS_SPOT_EDIT_DATE_FIELDS_INPUT
    - HISTORY_PROJECT_TYPE_TO_INFRASTRUCTURE
annotation_constants:
  file: com/zoho/automater/selenium/modules/projects/project/common/ProjectAnnotationConstants.java
  groups:
  - constant: CREATE_PROJECT
    value: createproject
  - constant: CREATE_AND_DELETE_PROJECT
    value: createanddeleteproject
  - constant: CREATE_PROJECT_WITH_MILESTONE_AND_MEMBERS
    value: createprojectwithmilestoneandmembers
  - constant: CREATE_REQUEST_FOR_PROJECT
    value: createrequestforproject
  - constant: CREATE_CHANGE_FOR_PROJECT
    value: createchangeforproject
  - constant: CREATE_BULK_CHANGE_FOR_PROJECT
    value: bulkchangeforproject
  - constant: CREATE_RELEASE_FOR_PROJECT
    value: createreleaseforproject
  - constant: BULK_CREATE
    value: bulkcreate
  - constant: CREATE_PROJECT_WITH_COMMENTS
    value: createprojectwithcomments
  - constant: DIFFERENT_PROJECTS_FOR_FILTERS
    value: differentprojectsforfilters
  - constant: CREATE_PROJECT_AND_TASK_WORKLOG
    value: createprojectandtaskworklog
  - constant: CREATE_AND_GET_DISPLAY_ID
    value: createAndGetDisplayID
  - constant: ADD_TASK_TEMPLATE
    value: addtasktemplate
  - constant: CREATE_PROJECT_WITH_MEMBERS
    value: createprojectwithmembers
  - constant: CREATE_PROJECT_WITH_MEMBERS_AND_TASK_WORKLOG
    value: createprojectwithmembersandtaskworklog
  - constant: CREATE_PROJECT_WITH_COMMENTS_AND_MEMBERS
    value: createprojectwithcommentsandmembers
  data:
  - constant: CREATE_PROJECT_USING_DEFAULT_PROJECT_TEMPLATE
    value: create_project_using_default_project_template
  - constant: CREATE_PROJECT_MANDATORY_FIELDS
    value: create_project_mandatory_fields
  - constant: CREATE_RELEASE_FOR_PROJECT
    value: create_release_for_project
  - constant: CREATE_PROJECT_STATUS_TO_ONHOLD
    value: create_project_status_to_onhold
  - constant: CEATE_PROJECT_STATUS_TO_CLOSED
    value: create_project_status_to_closed
  - constant: CREATE_PROJECT_STATUS_TO_CANCELED
    value: create_project_status_to_canceled
  - constant: CREATE_PROJECT_STATUS_TO_OPEN
    value: create_project_status_to_open
  - constant: ADD_COMMENT_UI
    value: add_comment_ui
  - constant: EDIT_COMMENT
    value: edit_comment
  - constant: ADD_COMMENT_API
    value: add_comment_api
  - constant: ADD_TASK
    value: add_task
  - constant: ADD_WORKLOG
    value: add_worklog
  - constant: ADD_TASK_FROM_TEMPLATE_VIA_ACTIONS
    value: add_task_from_template_via_actions
  - constant: ADD_MEMBER
    value: add_members
  - constant: BULK_CREATE_PROJECT_MANDATORY_FIELDS
    value: bulk_create_project_mandatory_fields
preprocess_groups: []
data_json_keys:
- Table_Settings
- add_comment_api
- add_comment_ui
- add_members
- add_task_from_template
- add_task_via_actions
- bulk_create_project_mandatory_fields
- change_casued_by_project_via_new_change
- copy_project
- copy_project_template
- create_project
- create_project_mandatory_fields
- create_project_status_to_canceled
- create_project_status_to_closed
- create_project_status_to_onhold
- create_project_status_to_open
- create_project_using_default_project_template
- create_project_with_owner
- create_projects_for_change_NR
- create_release_for_project
- details_spot_edit_date_fields_input
- details_spot_edit_textarea_fields_input
- details_spot_edit_using_search_input
- edit_comment
- edit_project
- history_actual_cost
- history_actual_hours
- history_estimated_cost
- history_estimated_hours
- history_owner
- history_percentage_completed
- history_priority
- history_priority_to_high
- history_priority_to_low
- history_priority_to_medium
- history_priority_to_normal
- history_project_code
- history_project_requester
- history_project_type_to_business
- history_project_type_to_infrastructure
- history_project_type_to_maintenance
- history_project_type_to_research
- history_status_Onhold
- history_status_canceled
- history_status_closed
- history_status_to_open
- list_info_criteria_title_search
- listview_search_by_column_input
- project_change_association_data
- project_data_association
- project_data_for_trigger
- rhs_owner
- rhs_priority_to_high
- rhs_priority_to_low
- rhs_priority_to_medium
- rhs_priority_to_normal
- rhs_status_to_canceled
- rhs_status_to_closed
- rhs_status_to_onhold
- spot_edit_actual_cost
- spot_edit_actual_hours
- spot_edit_estimated_cost
- spot_edit_estimated_hours
- spot_edit_owner
- spot_edit_percentage_completed
- spot_edit_project_code
- spot_edit_project_requester
- spot_edit_project_type_to_business
- spot_edit_project_type_to_infrastructure
- spot_edit_project_type_to_maintenance
- spot_edit_project_type_to_research
- spot_edit_status_to_canceled
- spot_edit_status_to_closed
- spot_edit_status_to_onhold
- spot_edit_status_to_open
