module: releasechecklist
entity: releasechecklist
actions_util:
  file: null
  methods: []
api_util:
  file: null
  methods: []
locators:
  file: com/zoho/automater/selenium/modules/releasechecklist/releasechecklist/common/ReleaseChecklistLocators.java
  interfaces:
    ReleaseChecklistLocators:
    - FEEDBACK_ICON
    - FEEDBACK_SEVERITY
    - FEEDBACK_SEVERITY_MAJOR
    - FEEDBACK_SUBJECT
    - FEEDBACK_DESCRIPTION
    - FEEDBACK_CAPTURE
    - FEEDBACK_CAPTURE_FULLSCREEN
    - FEEDBACK_CAPTURE_DONE
    - FEEDBACK_SUBMIT
    - LINK_COMMON
    - CHAT_MISSED
    - SWITCH_PORTAL
    - TERMS_AND_COND
    - WELCOME_TEXT
    - VERIFY_SKIP
    - SDP_CURRENT_APP_NAME
    - TABLE_HEADER_COLUMN
    - TABLE_HEADER_COLUMN_1
    - TABLE_ROW_DETAILS_USING_INDEX
    - TABLE_ROW_DETAILS_USING_INDEX_1
    - EXTENSION_CARD
    - PUBLISH_EXTENSION
    - EXTENSION_COMMENTS
    - EXTENSION_DETAILS_CLOSE
    - EXTENSION_COPY_URL
    - EXTENSION_CREATE
    - EXTENSION_URL_INPUT
    - EXTENSION_AGREE_TERMS
    - EXTENSION_AUTH
    - ACCOUNTS_CONTINUE_BUTTON
    - ACCOUNTS_LOGIN_BOX
    - ACCOUNTS_NEXT_BUTTON
    - ACCOUNTS_PASSWORD_BOX
    - ACCOUNTS_SIGNIN_BUTTON
    - ACCOUNTS_SHOW_IDP
    - ACCOUNTS_REMIND_ME_LATER
    - UPGRADE_IN_PAYMENTS
    - PAYMENTS_ADDITIONAL_TECHNICIANS
    - PAYMENTS_NO_OF_TECH
    - PAYMENTS_SELECT_ADDITIONAL_TECH
    - PAYMENTS_CONTINUE
    - PAYMENTS_MAKE_PAYMENT
    - PAYMENTS_NO_OF_TECH
    - PAYMENTS_MONTHLY
    - PAYMENTS_USE_BILLING_ADDRESS
    - PAYMENTS_COUNTRY
    - PAYMENTS_COUNTRY_SELECT
    - PAYMENTS_SELECTED_COUNTRY
    - PAYMENTS_EXPIRY_MONTH
    - PAYMENTS_EXPIRY_YEAR
    - PAYMENT_SUCCESS
    - GAPPS_ICON
    - GAPPS_EMAIL
    - GAPPS_NEXT_BUTTON
    - GAPPS_PASSWORD
    - O365_ICON
    - O365_EMAIL
    - O365_NEXT_BUTTON
    - O365_PASSWORD
    - USER_LIST_POPUP
    - ESM_PORTAL
    - INSTANCE_TOP_BAR
    - INSTANCE_SEARCH
    - Z_DIRECTORY_ICON
    - ESM_DOOR_NUMBER
    - INSTANCE_SEARCH_TEMPLATE
    - ESM_ORG_USER
    - ESM_SEARCH_USER
    - USER_SEARCH_PORTAL
    - CHECKBOX_IN_POPUP
    - COMMON_TABLE_DATA
    - COMMON_TABLE_DATA_SPAN
    - ESM_USER_NAME_FIELD
    - ESM_USER_EMAIL_FIELD
    - GADGETS_IFRAME
    - GADGETS_IFRAME_TABLE_HEADER
    - ATTACH_FROM_CLOUD_DROP_DOWN
    - ATTACH_FROM_CLOUD_ONEDRIVE
    - ATTACH_FROM_CLOUD_ONEDRIVE_AUTH
    - ATTACH_FROM_CLOUD_SUBMIT
    - ATTACH_FROM_CLOUD_GOOGLE_DRIVE
    - ATTACH_FROM_CLOUD_GOOGLE_AUTH
    - ATTACH_FROM_CLOUD_GOOGLE_AUTH_CONTINUE
    - ATTACH_FROM_CLOUD_GOOGLE_AUTH_ALLOW
    - ATTACH_FROM_CLOUD_GOOGLE_SEARCH
    - SURVEY_CONVO_DETAILS
    - AUTO_NOTIFICATION_CHECKBOX
    - CONVERSATION_CLOSED_DETAILS
    - FIRST_ROW_CHECKBOX
    - FOOTER_ICONS
    - LIVE_CHAT_ICON
    - CHAT_IFRAME_REQUESTER
    - CHAT_NOW
    - DISCOVER_PANE
    - KEYBOARD_SHORTCUT
    - KEYBOARD_SHORTCUT_TOGGLE
    - CHAT_QUESTION
    - START_CHAT
    - CHAT_IFRAME
    - CHAT_HISTORY_FIRST_ROW
    - CHAT_CLOSE
    - CHAT_PICKUP
    - CHAT_MESSAGE_AREA
    - CHAT_CONVERT_AS_REQUEST
    - CHAT_ASSOCIATED_DATA
    - END_CHAT
    - SDP_WIDGET
    - CONVERT_AS_TICKET
    - SELECT_CHAT_USER
    - SELECT_CHAT_USER_INPUT
    - ALL_CHAT_USERS
    - SELECT_CHAT_USER_DROPDOWN
    - IMPORT_SELECT_MODULE
    - IMPORT_FILE
    - IMPORT_JOB_DATE
    - IMPORT_SELECT_PROJECT_TEMPLATE
    - CUSTOM_WIDGET_NAME
    - IMPORT_FILE
    - JIRA_INTEG_CARD
    - JIRA_FORM
    - JIRA_INTEG_ATTACH_LINK
    - ALL_USERS_FILTER
    - SIGN_UP_NOW
    - LOGIN_URL_FIELD
    - LOGOUT_URL_FIELD
    - SAML_CERTIFICATE
    - SAML_DELETE_BUTTON
    - VIEW_CURRENT_SAML_CONFIGURATION
    - VERIFY_URL_CONTENT
    - SELECT_MODULE_FIELD
    - ADD_USER_FORM_INPUT_FIELD
    - ADD_USER_FORM_RADIO_FIELD
    - ADD_USER_FORM_SELECT_FIELD
data_constants:
  file: com/zoho/automater/selenium/modules/releasechecklist/releasechecklist/common/ReleaseChecklistDataConstants.java
  classes:
    ReleaseChecklistDataConstants:
    - ORGUSER_WITH_FIELDS
    - CHECKLIST_PAYMENTS
    - CHECKLIST_SIGNUP
annotation_constants:
  file: null
  groups: []
  data: []
preprocess_groups: []
data_json_keys: []
