module: releases
entity: releasereminder
actions_util:
  file: null
  methods: []
api_util:
  file: com/zoho/automater/selenium/modules/releases/releasereminder/utils/ReleaseReminderAPIUtil.java
  methods:
  - name: createReleaseWithReminder
    return_type: HashMap<String, String>
    params: String release, String reminder
    purpose: ''
locators:
  file: com/zoho/automater/selenium/modules/releases/releasereminder/common/ReleaseReminderLocators.java
  interfaces:
    ReleaseReminderLocators: []
    ReleaseReminderDetailsview:
    - TYPE_REMINDER_NAME
    - VERIFY_REMINDER_NAME
    - SELECT_REMINDER_CHECKBOX_USING_ENTITYID
    - CLICK_ROW_ACTIONS_WITH_ENTITYID
    - MODIFY_REMINDER_STATE_TO_FILTER_DROPDOWN
    - SELECT_COMPLETED_STATE
    - VERFIY_STRIKETHROUGH_COMPLETE_STATE_BY_ENTITYID
    - SELECT_OPEN_STATE
    - VERFIY_NO_STRIKETHROUGH_OPEN_STATE_BY_ENTITYID
    ReleaseReminderPopup:
    - VERIFY_NEW_REMINDER_TEXT_IN_POPUP
    - VERIFY_EDIT_REMINDER_TEXT_IN_POPUP
    - CLICK_DATE_FIELD_IN_POPUP
data_constants:
  file: com/zoho/automater/selenium/modules/releases/releasereminder/common/ReleaseReminderDataConstants.java
  classes:
    ReleaseReminderDataConstants:
    - EDIT_REMINDER
    - API_VALID_INPUT_GENERAL_TEMPLATE
    - ASSOCIATED_GROUP
    - API_VALID_INPUT_GENERAL_TEMPLATE_WITHOUT_SITE_GROUP
    - ASSOCIATED_CUSTOM_SITE
    - CLOSED_REMINDER
    - NEW_REMINDER
annotation_constants:
  file: com/zoho/automater/selenium/modules/releases/releasereminder/common/ReleaseReminderAnnotationConstants.java
  groups:
  - constant: CREATE_RELEASE
    value: createrelease
  - constant: CREATE_RELEASE_WITH_REMINDER
    value: createreleasewithreminder
  data:
  - constant: API_VALID_INPUT_GENERAL_TEMPLATE
    value: api_valid_input_general_template
  - constant: API_VALID_INPUT_GENERAL_TEMPLATE_WITHOUT_SITE_GROUP
    value: api_valid_input_general_template_without_site_group
  - constant: ADD_REMINDER
    value: new_reminder
  - constant: EDIT_REMINDER
    value: edit_reminder
  - constant: CLOSED_REMINDER
    value: closed_reminder
preprocess_groups:
- name: createrelease
  creates_count: 0
  local_storage_keys:
  - releaseId
  - reminderId
- name: createreleasewithreminder
  creates_count: 0
  local_storage_keys:
  - releaseId
  - reminderId
data_json_keys: []
