module: requests
entity: task
actions_util:
  file: null
  methods: []
api_util:
  file: null
  methods: []
locators:
  file: com/zoho/automater/selenium/modules/requests/task/common/TaskLocators.java
  interfaces:
    TaskLocators:
    - LIST_VIEW
    - SINGLE_TASK_TITTLE_LOCOTOR
    DetailView:
    - CREATED_BY
    - REQUESTER_MOREDETAILS
    - MOREDETAILS_POPUP
    - WORKLOG_TIME_LOCATOR
    - WORKLOG_TIME_INITIATED
    - ADD_WORKLOG_TIME_LOCATOR
    - TYPE_INPUT_TEXT
data_constants:
  file: com/zoho/automater/selenium/modules/requests/task/common/TaskDataConstants.java
  classes:
    TaskDataConstants:
    - UI_REQUESTTASK1
    - UI_REQUESTTASK2
    - API_REQUESTTASK1
    - API_REQUESTTASK2
annotation_constants:
  file: null
  groups: []
  data: []
preprocess_groups: []
data_json_keys:
- API_RequestTask1
- API_RequestTask2
- UI_RequestTask1
- UI_RequestTask2
