module: requests
entity: worklog
actions_util:
  file: null
  methods: []
api_util:
  file: null
  methods: []
locators:
  file: com/zoho/automater/selenium/modules/requests/worklog/common/WorklogLocators.java
  interfaces:
    WorklogLocators: []
data_constants:
  file: com/zoho/automater/selenium/modules/requests/worklog/common/WorklogDataConstants.java
  classes:
    WorklogDataConstants:
    - WORKLOG_DATA_FOR_OH
    - UI_WORKLOG1
    - WORKLOG_DATA_FOR_RESOLUTION
annotation_constants:
  file: null
  groups: []
  data: []
preprocess_groups: []
data_json_keys:
- UI_Worklog1
- Worklog_Data_For_Resolution
- worklog_data_for_oh
