module: requests
entity: worklog
actions_util:
  file: null
  methods: []
api_util:
  file: null
  methods: []
locators:
  file: null
  interfaces: {}
data_constants:
  file: com/zoho/automater/selenium/modules/requests/worklog/common/WorklogDataConstants.java
  classes:
    WorklogDataConstants:
    - WORKLOG_DATA_FOR_OH
    - UI_WORKLOG1
    - WORKLOG_DATA_FOR_RESOLUTION
annotation_constants:
  file: null
  groups: []
  data: []
preprocess_groups: []
data_json_keys:
- UI_Worklog1
- Worklog_Data_For_Resolution
- worklog_data_for_oh
data_json_deep:
  total_entries: 3
  field_frequency:
    time_spent: 1
    worklog: 1
    owner: 1
    start_time: 1
    end_time: 1
  all_placeholders:
  - custom_nextHour
  - custom_previousHour
  - user_name
  reuse_groups_count: 0
  entries:
    UI_Worklog1:
      fields:
      - time_spent
      placeholders: []
      local_storage_keys_required: []
      purpose: ui_form
    worklog_data_for_oh:
      fields:
      - worklog
      placeholders:
      - user_name
      - custom_previousHour
      - custom_nextHour
      local_storage_keys_required:
      - previousHour
      - nextHour
      purpose: ui_form
    Worklog_Data_For_Resolution:
      fields:
      - owner
      - start_time
      - end_time
      placeholders:
      - user_name
      - custom_previousHour
      - custom_nextHour
      local_storage_keys_required:
      - previousHour
      - nextHour
      purpose: ui_form
